### ISSUE TITLE
Maybe use go tpl go generate code?

### ISSUE THREAD

**Issue by SuperGod** [AllenDang/cimgui-go#1]
Hi, I have tried to use the go template to implement the go binding of cimgui, but of course I haven't finished(Because there are some complex C callback functions). 
But I still think that template is more simpler, so why not use template to implement it? 

Another of my projects uses templates to implement: https://github.com/ztrade/ctpgen/blob/main/tpl/api.tpl

If you need, I can give you my unfinished template or provide some help

**Comment by AllenDang** [comment]
@SuperGod I will take a look for it. Thanks for sharing!

**Comment by AllenDang** [comment]
@SuperGod I see. It should be a better solution than manipulate string in code.

**Comment by gucio321** [comment]
@AllenDang In my opinion we didn't go this way and the current codebase is a bit to mature to start from scratch again. Over that I don't think manipulating strings in code is a wrong idea - it works for now. Imao we can close this, can't we?
