### ISSUE TITLE
Cannot use GetTexDataAsAlpha8

### ISSUE THREAD

**Issue by neclepsio** [AllenDang/cimgui-go#10]
If I use `C.uchar`, as stated in docs, I get: `cannot use &pixels (value of type *_Ctype_uchar) as *cimgui._Ctype_uchar value in argument to io.GetFonts().GetTexDataAsAlpha8`; while `cimgui._Ctype_uchar` is not exported.

**Comment by AllenDang** [comment]
What's your code looks like?

**Comment by neclepsio** [comment]
io := imgui.GetIO()
	var pixels imgui._Ctype_uchar
	var width int32
	var height int32
	io.GetFonts().GetTexDataAsAlpha8(&pixels, &width, &height)

**Comment by AllenDang** [comment]
Try use io.GetFonts().GetTextureDataAsAlpha8, it's a wrapped version.

**Comment by AllenDang** [comment]
I removed the auto-generated version of GetTexData... related functions to avoid further miss usage.

**Comment by gucio321** [comment]
@neclepsio did you fix the issue?

**Comment by neclepsio** [comment]
I stopped using this wrapper because of other problems, I will try again later, when #11 and #12 will be closed (there are pull approved requests for them).

**Comment by gucio321** [comment]
> I stopped using this wrapper because of other problems, I will try again later, when https://github.com/AllenDang/cimgui-go/issues/11 and https://github.com/AllenDang/cimgui-go/issues/12 will be closed (there are pull approved requests for them).

Yah, there are PRs. I'll try to finish them today

**Comment by gucio321** [comment]
@neclepsio the PRs are merged, could you try to reproduce this now?

**Comment by neclepsio** [comment]
Sorry for being so late, I needed to port my entire application from `inkyblackness/imgui-go`, which I just finished.

The wrapped version crashes in C code.

    Exception 0xc0000005 0x0 0x30 0x7ff63b4fdb44
    PC=0x7ff63b4fdb44
    signal arrived during external code execution

    runtime.cgocall(0x7ff63b3f95c0, 0xc00149b500)
            [...]/Go/go1.19.3/src/runtime/cgocall.go:158 +0x4a fp=0xc00149b4d8 sp=0xc00149b4a0 pc=0x7ff63afa4d2a
    github.com/AllenDang/cimgui-go._Cfunc_ImFontAtlas_GetTexDataAsAlpha8(0x28ae37e2d80, 0xc0000902f0, 0xc000530b48, 0xc000530b4c, 0xc000530b50)
            _cgo_gotypes.go:4671 +0x52 fp=0xc00149b500 sp=0xc00149b4d8 pc=0x7ff63b2153f2
    github.com/AllenDang/cimgui-go.FontAtlas.TextureDataAsAlpha8.func1(0xc00149b598?, 0x7ff63b2aa51a?, 0x28ae37dd618?, 0x28ae37e2d80?, 0x0?)
            [...]/src/github.com/neclepsio/cimgui-go/util.go:62 +0x9c fp=0xc00149b560 sp=0xc00149b500 pc=0x7ff63b2dfefc
    github.com/AllenDang/cimgui-go.FontAtlas.TextureDataAsAlpha8(0x28ae37dd618?)
           [...]/src/github.com/neclepsio/cimgui-go/util.go:62 +0x7d fp=0xc00149b5c0 sp=0xc00149b560 pc=0x7ff63b2dfe1d
    [...]

**Comment by neclepsio** [comment]
I can confirm this is solved.
