### ISSUE TITLE
Ability to set position of main (platform) window

### ISSUE THREAD

**Issue by runrc** [AllenDang/cimgui-go#104]
Is it possible to set the position of the main (platform) window?

For example, the GLFW backend implements a [glfwSetWindowPos](https://www.glfw.org/docs/3.3/group__window.html#ga1abb6d690e8c88e0c8cd1751356dbca8) function, however this is not exposed in cimgui-go. Is it possible to call these platform functions?

**Comment by eliasdaler** [comment]
cc:@AllenDang @gucio321 
I feel like wrapping glfw manually was a mistake. What if it was using [go-gl/glfw](https://github.com/go-gl/glfw)?
This would make using all of GLFW much easier for new users.

@runrc, you can probably get a handle which gets returned by `imgui.CreateGlfwWindow` and then wrap `glfwSetWindowsPos` manually via CGo, and pass this handle to this wrapper.

**Comment by runrc** [comment]
@eliasdaler Yes, I could manually wrap and call methods via CGo, but that is not an ideal solution. 

As mentioned, using [go-gl/glfw](https://github.com/go-gl/glfw) (or similar) would allow users more control over backend / platform specific features.

**Comment by eliasdaler** [comment]
By the way, do you need to use GLFW? 

You can try using ebiten-imgui and Ebitengine has quite a nice interface for manipulating the window/drawing things.

I didn't update my fork of [ebiten-imgui](https://github.com/eliasdaler/ebiten-imgui/tree/cimgui-go) for a while, but I might do it soon to sync with the latest changes in cimgui-go.

**Comment by runrc** [comment]
No there is no direct requirement to use GLFW. 
Happy to use [ebiten-imgui](https://github.com/eliasdaler/ebiten-imgui/tree/cimgui-go) and see how it performs. A sync up with the latest changes in cimgui-go would be great.
Even between would be an abstraction layer that allows users to choose Ebitengine or GLFW (or other alternative) backend / platform.

**Comment by eliasdaler** [comment]
The abstraction layer is not needed. cimgui-go is already an abstraction layer
My ebiten-imgui fork doesn't use anything from backend.go or GLFW
