### ISSUE TITLE
cannot use _Ctype_long(p.S)  as type _Ctype_longlong

### ISSUE THREAD

**Issue by nullptr-ref** [AllenDang/cimgui-go#105]
Hello, 

While trying to build the example using the latest stable version of Go and the latest version of cimgui-go the compilation fails with:

`C:\Users\ArtoS\go\pkg\mod\github.com\!allen!dang\cimgui-go@v0.0.0-20230123025400-8ac6282740cd\extra_types.go:205:25: cannot use _Ctype_long(p.S) (value of type _Ctype_long) as type _Ctype_longlong in struct literal`

In the end, I had to replace the code in the extra_types.go (on line 205) with:

`return C.ImPlotTime{S: C.longlong(p.S), Us: C.int(p.Us)}`

OS: Windows
Compiler: gcc version 12.2.0 (Rev6, Built by MSYS2 project) 64 bit

Let me know if you need more information.

**Comment by gucio321** [comment]
oh, ok, I see.
This should actually be `C.xlong`, because refering to code from `extra_types.h`:
```h
#pragma once

#ifdef __WIN32
typedef unsigned long long xlong;
#else
typedef unsigned long xlong;
#endif
```

let me open a PR

**Comment by gucio321** [comment]
@nullptr-ref could you pleas check if https://github.com/AllenDang/cimgui-go/pull/106 works on your machine

**Comment by nullptr-ref** [comment]
@gucio321 

#106 won't work as you have defined `xxlong` just for the OS's other than Windows and there is a conflict as there are 2x xlong definitions. 

the extra_types.h should be:

```#ifdef __WIN32
typedef unsigned long long xlong;
typedef long long xxlong;
#else
typedef unsigned long xlong;
typedef long xxlong;
#endif
```

^ With that modification to your commit, it builds correctly.

**Comment by gucio321** [comment]
@nullptr-ref pls try again - it should be ok now

**Comment by gucio321** [comment]
also, I'll improve our workflows to make them catch such an errors (see #107 )

**Comment by nullptr-ref** [comment]
The latest changes to #106 resolve the issue.
