### ISSUE TITLE
How to programmatically close main window and exit the application?

### ISSUE THREAD

**Issue by runrc** [AllenDang/cimgui-go#108]
What is the best way to programmatically close the main window and exit the application?

Additionally, where is best to ask these types of questions? Should we raise a discussion issue and thus create a set of FAQ's / guidelines?

**Comment by nullptr-ref** [comment]
You can use the Discussions page -> #47 

As for your question, you can always use os.Exit(0) to force quit the application.

**Comment by runrc** [comment]
@nullptr-ref Will open a discussion for further questions. Thanks.
I would like to perform a programmatic graceful close rather than a brute force system exit.

**Comment by runrc** [comment]
Additionally, allowing a programmatic close would mean we could intercept signals and close the application gracefully

**Comment by WinPooh32** [comment]
@runrc, I binded [function](https://www.glfw.org/docs/latest/group__window.html#ga49c449dde2a6f87d996f4daaa09d6708) for closing window:
```
window.SetWindowShouldClose(true)
```

You can test it by adding this line to go.mod:
```
replace github.com/AllenDang/cimgui-go => github.com/WinPooh32/cimgui-go v0.0.0-20230126114204-22d2da4b5eed
```

**Comment by runrc** [comment]
@WinPooh32 Thank you. I have verified your change and it works exactly as expected. The main window is closed gracefully when the function is called.

BTW - the function is,
```go
window.SetShouldClose(true)
```

not `window.SetWindowShouldClose(true)` 

Thank you once again for providing this.
