### ISSUE TITLE
Shouldn't out arguments be returned values?

### ISSUE THREAD

**Issue by neclepsio** [AllenDang/cimgui-go#11]
For example:

    func GetDrawCursorPos(pOut *ImVec2)

should be:

    func GetDrawCursorPos() ImVec2

**Comment by AllenDang** [comment]
It's auto generated code, process arguments is a lot easier than recognize out value.

**Comment by sonoro1234** [comment]
this function have nonUDT=1 to let recognize it should be a return value

**Comment by AllenDang** [comment]
@sonoro1234 You could have a try and raise a PR

**Comment by sonoro1234** [comment]
Dont know go languaje.
