### ISSUE TITLE
Unable to properly position next window if viewports enabled

### ISSUE THREAD

**Issue by pztrn** [AllenDang/cimgui-go#112]
On 84cf33bf89a2.

I'm trying to implement a status bar in my window using [this](https://github.com/ocornut/imgui/issues/3518#issuecomment-1008090905) as example. I got the following code:

```go
package main

import imgui "github.com/AllenDang/cimgui-go"

func main() {
	window := imgui.CreateGlfwWindow("Statusbar Test", 900, 900, 0)
	window.Run(render)
}

func render() {
	opened := true

	windowSize := imgui.WindowViewport().WorkSize() // Tried Size(), same value returned.
	lineHeight := imgui.FrameHeightWithSpacing()

	nextPos := imgui.Vec2{X: 0, Y: windowSize.Y - lineHeight}
	nextSize := imgui.Vec2{X: windowSize.X, Y: lineHeight}

	imgui.SetNextWindowPos(nextPos)
	imgui.SetNextWindowSize(nextSize)

	if imgui.BeginV(
		"##mainwindow_status_bar",
		&opened,
		imgui.WindowFlagsNoDecoration|
			imgui.WindowFlagsNoInputs|
			imgui.WindowFlagsNoMove|
			imgui.WindowFlagsNoScrollWithMouse|
			imgui.WindowFlagsNoSavedSettings|
			imgui.WindowFlagsNoDocking|
			imgui.WindowFlagsNoBringToFrontOnFocus,
	) {
		imgui.Text("I'm a status bar!")

		imgui.End()
	}
}
```

First, new window isn't in the very bottom of main window, even if I remove `lineHeight` substraction:

![изображение](https://user-images.githubusercontent.com/869402/216374632-27c4c913-5929-49fc-9f70-2fe9878dd020.png)

Second, if I resize main window, I got that glitch:

![изображение](https://user-images.githubusercontent.com/869402/216374907-5d373e45-1be1-401e-b1de-9543648cbdea.png)

After moving window to position where viewport's `(0,0)` was - status bar window reappeared in main window:

![изображение](https://user-images.githubusercontent.com/869402/216375668-faadb199-7ee2-4621-9d1d-e0c412afcaf6.png)

I can resize it and status bar will stay on it's position until I move main window. Then status bar window instantly jumps out and situation from second screen repeats.

*(also, notice that status bar window isn't in the very bottom of window)*.

The the very funny thing: when I tried:

```go
nextSize := imgui.Vec2{X: windowSize.X - 100, Y: lineHeight}
```

I got:

https://user-images.githubusercontent.com/869402/216377873-99f02f76-8410-4ff0-977f-15a22f189eb5.mp4

I'll try to write C++ code to check vanilla imgui (as I suspect current cimgui-go using docking branch) and reproduce. Looks like something in wrapper is borked.

**Comment by pztrn** [comment]
Yes, something is wrong either with bindings or docking branch. Following code in C++ works perfectly fine:

```cpp
        ImGuiViewport *viewport = ImGui::GetMainViewport();
        float lineHeight = ImGui::GetTextLineHeight();

        ImVec2 nextWindowPos = ImVec2(0.0f, viewport->Size.y - lineHeight);
        ImVec2 nextWindowSize = ImVec2(viewport->Size.x, lineHeight);

        ImGui::SetNextWindowPos(nextWindowPos);
        ImGui::SetNextWindowSize(nextWindowSize);

        ImGuiWindowFlags flags =
            ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoInputs |
            ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollWithMouse |
            ImGuiWindowFlags_NoSavedSettings |
            ImGuiWindowFlags_NoBringToFrontOnFocus;

        if (ImGui::Begin("##statusbar", &show_statusbar, flags))
        {
            ImGui::Text("I am statusbar!");

            ImGui::End();
        }
```

Transformed accordingly go code:

```go
package main

import (
	"log"

	imgui "github.com/AllenDang/cimgui-go"
)

func main() {
	window := imgui.CreateGlfwWindow("Statusbar Test", 900, 900, 0)
	window.Run(render)
}

func render() {
	opened := true

	viewport := imgui.MainViewport()
	lineHeight := imgui.FrameHeightWithSpacing()

	nextPos := imgui.Vec2{X: 0, Y: viewport.Size().Y - lineHeight}
	nextSize := imgui.Vec2{X: viewport.Size().X, Y: lineHeight}

	log.Println(nextPos, nextSize)

	imgui.SetNextWindowPos(nextPos)
	imgui.SetNextWindowSize(nextSize)

	if imgui.BeginV(
		"##mainwindow_status_bar",
		&opened,
		imgui.WindowFlagsNoDecoration|
			imgui.WindowFlagsNoInputs|
			imgui.WindowFlagsNoMove|
			imgui.WindowFlagsNoScrollWithMouse|
			imgui.WindowFlagsNoSavedSettings|
			imgui.WindowFlagsNoDocking|
			imgui.WindowFlagsNoBringToFrontOnFocus,
	) {
		imgui.Text("I'm a status bar!")

		imgui.End()
	}
}
```

Still like in first post.

**Comment by AllenDang** [comment]
@pztrn Does the C++ version with docking brach works as expect?

**Comment by pztrn** [comment]
Yes, it works fine (yet position should be adjusted):

![изображение](https://user-images.githubusercontent.com/869402/216607141-1c730523-978c-48c8-9979-e2686a64e1c9.png)

**Comment by pztrn** [comment]
I think I found the issue - it is configuration flag `ViewportsEnable`. When I disable it from imgui demo window in my app everything become in line with C++ version.

**Comment by AllenDang** [comment]
@pztrn Seems it's a bug of viewport in docking branch. As a workaround, you could use a single window, like giu.SingleWindow's concept, as main container and create bottom status bar inside it.

**Comment by gucio321** [comment]
@AllenDang btw, shouldn't we update our imgui version?

**Comment by pztrn** [comment]
For me it was enough to disable viewports feature via configuration flags as I shown before. I'll change issue title to reflect actual bug.

**Comment by AllenDang** [comment]
@gucio321 Yes, we should update imgui version according to its releases.

**Comment by gucio321** [comment]
And which release are we using right now

**Comment by AllenDang** [comment]
From imgui.h, it's **// dear imgui, v1.89 WIP**

**Comment by sonoro1234** [comment]
Were ig.UpdatePlatformWindows() and ig.RenderPlatformWindowsDefault() used?

**Comment by gucio321** [comment]
@pztrn I figured it out in giu already:
Its because in docking branch, viewport has its own position in its state and SetNextWindowPos is not relative to viewport anymore.
So you should change your code:
```go
        // ...
        nextPos := imgui.Vec2{X: viewport.Pos().X, Y: viewport.Pos().Y + viewport.Size().Y - lineHeight}
        // ...
```
