### ISSUE TITLE
Algebra for ImVec2 and ImVec4

### ISSUE THREAD

**Issue by neclepsio** [AllenDang/cimgui-go#12]
Please, provide algebraic functions for ImVec2 and ImVec4, e.g.:

    pos := cimgui.ImVec2{}
    pos = pos.Plus(cimgui.ImVec2{}).Minus(cimgui.ImVec2{}).Times(2)

**Comment by AllenDang** [comment]
You could raise a PR and I'm happy to merge it.

**Comment by gucio321** [comment]
In my opinion, method naming should be exact the same as in GO's `image.Point` type

```console
[~ (0) ]$ go doc image.point
package image // import "image"

type Point struct {
	X, Y int
}
    A Point is an X, Y coordinate pair. The axes increase right and down.

var ZP Point
func Pt(X, Y int) Point
func (p Point) Add(q Point) Point
func (p Point) Div(k int) Point
func (p Point) Eq(q Point) bool
func (p Point) In(r Rectangle) bool
func (p Point) Mod(r Rectangle) Point
func (p Point) Mul(k int) Point
func (p Point) String() string
func (p Point) Sub(q Point) Point
```

sadly, wy can't just turn ImVec2 into image.Point, since for some reason ImVec2 is `X, Y float32` instead `X, Y int` (like image.Point)

**Comment by neclepsio** [comment]
I just used imgui-go names.

**Comment by eliasdaler** [comment]
Let's go with what is generally used for implementing vectors in languages which don't have operator overloads: "Add", "Sub", etc.

**Comment by gucio321** [comment]
hmm, I don't think it is a good idea to add custom stuff to auto-generated code...
@AllenDang @eliasdaler what do you think? Is it expected logic here?

**Comment by eliasdaler** [comment]
I don't see issues with that. We can't have Dear ImGui's API map 1-to-1 to Go. We can't make "operator+" in Go, so we're making "Add" function for user convenience.

**Comment by AllenDang** [comment]
We could provide helper functions, there already lots of them. For naming convention, follow go std lib is a good thought.

**Comment by gucio321** [comment]
Ok, so opening a PR
