### ISSUE TITLE
How to use the "onDrop of external files" example from giu in cimgui-go?

### ISSUE THREAD

**Issue by SeyRyuu** [AllenDang/cimgui-go#123]
Hey,

i want to migrate the [onDrop example for external files from AllenDang/giu](https://github.com/AllenDang/giu/blob/master/examples/ondrop/ondrop.go) to cimgui-go code, but i hit a problem.

If i use the `cimgui.CreateGlfwWindow()` func to create a new `GLFWwindow` element i can not setup the drop callback (func `SetDropCallback()`) like in the giu example.

Is this function missing (like a different one in #110), or is there now a different way to archive this?

**Comment by gucio321** [comment]
if it is a GLFW function I think that, yeah, it is not exposed yet

**Comment by gucio321** [comment]
> GLFWAPI GLFWdropfun glfwSetDropCallback(GLFWwindow* window, GLFWdropfun callback);

this one needs to be exported to go

**Comment by SeyRyuu** [comment]
Thanks for your reply @gucio321!
Hmm, yeah seems to be this one. Sadly I don't know how to wrap or implement this into cimgui-go.
Can you migrate this @gucio321, or someone else?

**Comment by gucio321** [comment]
ok, let me do this (if I forget about this, feel free to ping me :smile:)

**Comment by SeyRyuu** [comment]
Cool, thank you!

**Comment by gucio321** [comment]
great to hear!
