### ISSUE TITLE
codegen: make a separated module

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#139]
Hi there
`cmd/codegen` should actually be a separated module, because:
- it is actually not dependent on cimgui code anyhow
- it should have its own dependencies list (currently, cimgui-go does not rely on glg logger anyhow, but cimgui users needs to pull it to use framework)
- it makes development process a bit annoying (I'm using vim-go sometimes, vim-go uses gopls and gopls needs to (re)build whole C code and it often takes about minute to just close vim :cry:)

The problem is that I have no idea how should it be handled in `Makefile` (how to make go to run code from module)

**Comment by AllenDang** [comment]
I agree. Let's go ahead.
