### ISSUE TITLE
Improved readme: works on (at least some) linux distributions, too :heart_eyes:

### ISSUE THREAD

**Issue by DannyOneway** [AllenDang/cimgui-go#14]
`README.md` says right now:

> It works on macOS(arm64/x86) and windows(x64) now, idealy linux should works but I don't have a linux machine to test it. Check out examples, cd in and go run ..

Just did with some latest Arch Linux/KDE distribution, worked fine out of the box... will checkout on Pop! OS/Gnome in the upcoming few days, too... gonna comment that here, too.

Thank you all for your work regarding imgui+golang... really appreciate all that effort... makes my "learning Go while fiddling with some cross-platform UI" really, really fun and enjoyable :heart:

![Screenshot_20220924_113630](https://user-images.githubusercontent.com/1935159/192091125-b4cc3b1c-e014-46f8-a634-2af03dc63cc1.png)

**Comment by gucio321** [comment]
I confirm - works on Fedora Workstation 36

<details><summary><code>/etc/os-release</code></summary>

```console
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

</details>

(libraries installed just like for giu)

**Comment by AllenDang** [comment]
Thanks guys! README is updated.
