### ISSUE TITLE
How to use UTF8 strings?

### ISSUE THREAD

**Issue by sertraline** [AllenDang/cimgui-go#144]
Given Go strings assume content to be UTF8 by default I would expect it to work, instead I get ????? as the output.

```go
func afterCreateContext() {
	io := imgui.CurrentIO()
	io.Fonts().AddFontFromFileTTF("NotoSansCJK-Regular.ttc", float32(18))
}
```  
(note: CJK is a Chinese/Japanese/Korean font)

```go
imgui.TableNextColumn()
imgui.Text("123")

imgui.TableNextColumn()
imgui.Text("こんにちは")
```  

![image](https://files.catbox.moe/wyrwul.png)

**Comment by gucio321** [comment]
I think you need to register glyph rangers (like you would do in imgui)

**Comment by sertraline** [comment]
Does not seem to have any effect.
```go
ranges := imgui.NewGlyphRange()
builder := imgui.NewFontGlyphRangesBuilder()
builder.AddRanges(io.Fonts().GlyphRangesJapanese())
builder.AddText("こんにちは")
builder.BuildRanges(ranges)

io.Fonts().AddFontFromFileTTFV("NotoSansCJK-Regular.ttc", float32(18), 0, ranges.Data())
io.Fonts().Build()
```  

`io.Fonts().AddFontFromFileTTFV("NotoSansCJK-Regular.ttc", float32(18), 0, io.Fonts().GlyphRangesJapanese())`  - no effect as well.
Trying different ranges on this font (GlyphRangesDefault) will result in segfault.

Full example as follows:
<details>
  <summary>Spoiler</summary>  

  ```go
package main

import (
	imgui "github.com/AllenDang/cimgui-go"
)

var (
	showDemoWindow bool
	backend        imgui.Backend
	buf            string
)

func renderWindow() {
	basePos := imgui.MainViewport().Pos()
	opened := true
	imgui.SetNextWindowSizeV(imgui.NewVec2(400, 400), imgui.CondOnce)
	imgui.SetNextWindowPosV(imgui.NewVec2(basePos.X, basePos.Y), imgui.CondOnce, imgui.NewVec2(0, 0))
	imgui.PushItemWidth(float32(-1))

	imgui.BeginV("Window", &opened, imgui.WindowFlagsNoMove|imgui.WindowFlagsNoTitleBar|imgui.WindowFlagsNoResize)

	if imgui.CollapsingHeaderBoolPtrV("Presets", nil, imgui.TreeNodeFlagsDefaultOpen) {
		imgui.BeginTable("Test", 2)

		imgui.TableSetupColumn("Item")
		imgui.TableSetupColumn("Value")
		imgui.TableHeadersRow()

		imgui.TableNextColumn()
		imgui.Text("123")

		imgui.TableNextColumn()
		imgui.Text("こんにちは")

		imgui.EndTable()
	}
	imgui.End()
}

func afterCreateContext() {
	io := imgui.CurrentIO()

	ranges := imgui.NewGlyphRange()
	builder := imgui.NewFontGlyphRangesBuilder()
	builder.AddRanges(io.Fonts().GlyphRangesJapanese())
	builder.AddText("こんにちは")
	builder.BuildRanges(ranges)

	io.Fonts().AddFontFromFileTTFV("NotoSansCJK-Regular.ttc", float32(18), 0, ranges.Data())
	io.Fonts().Build()
}

func loop() {
	imgui.ShowDemoWindowV(&showDemoWindow)
	renderWindow()
}

func beforeDestroyContext() {
}

func main() {
	backend = imgui.CreateBackend()
	backend.SetAfterCreateContextHook(afterCreateContext)
	backend.SetBeforeDestroyContextHook(beforeDestroyContext)

	backend.SetBgColor(imgui.NewVec4(0.0, 0.0, 0.0, 0.0))
	backend.SetTargetFPS(60)

	backend.CreateWindow("kao", 400, 400, 0)

	backend.Run(loop)
}
  ```  
  
</details>  

Font used in example: [https://github.com/notofonts/noto-cjk/blob/main/Sans/OTC/NotoSansCJK-Regular.ttc](https://github.com/notofonts/noto-cjk/blob/main/Sans/OTC/NotoSansCJK-Regular.ttc)

**Comment by JetSetIlly** [comment]
You'll have to set merge mode in the font config before you call the AddFontFromFileTTFV() function.

Otherwise, you'll need to use PushFont() - and PopFont() - in order to use the font you've added.

**Comment by sertraline** [comment]
```go
io := imgui.CurrentIO()

config := imgui.NewFontConfig()
config.SetMergeMode(true)

io.Fonts().AddFontDefault()
io.Fonts().AddFontFromFileTTFV("NotoSansCJK-Regular.ttc", float32(18), config, imgui.NewFontAtlas().GlyphRangesJapanese())
io.Fonts().Build()
```
Has no effect (but it does use default font). By removing `io.Fonts().AddFontDefault()` and config GUI will switch to new font and PushFont has no effect, I still see ???? instead of glyphs.

**Comment by gucio321** [comment]
@sertraline could you try with C++ version of Dear ImGui? I don't think it is an issue in cimgui-go tbh.

**Comment by sertraline** [comment]
Using imgui demo example everything works as intended, that is to say I don't have to push or pop fonts or merge configs.  

![Screenshot_20230511_004326](https://github.com/AllenDang/cimgui-go/assets/36751007/ed582bb9-87b6-4f94-b175-456a90d2b81d)

```go
io.Fonts().AddFontFromFileTTFV("NotoSansCJK-Regular.ttc", float32(16), 0, io.Fonts().GlyphRangesJapanese())
```  
Go equivalent of this works, font is added and is used by application, but UTF-8 characters are displayed as ??? nevertheless.  

In imgui ranges return a pointer to array of ImWChar, which in turn is either unsigned short or unsigned int. Go code returns a pointer to rune.
```C++
typedef unsigned short ImWchar16;   // A single decoded U16 character/code point. We encode them as multi bytes UTF-8 when used in strings.
typedef unsigned int ImWchar32;     // A single decoded U32 character/code point. We encode them as multi bytes UTF-8 when used in strings.
#ifdef IMGUI_USE_WCHAR32            // ImWchar [configurable type: override in imconfig.h with '#define IMGUI_USE_WCHAR32' to support Unicode planes 1-16]
typedef ImWchar32 ImWchar;
#else
typedef ImWchar16 ImWchar;
```  
Could this be related to the issue?

**Comment by sertraline** [comment]
Apparently this was an issue with the font itself. `NotoSansCJKjp-Medium.otf` with Japanese glyph ranges worked. CJK regular does not work.

I don't know why C++ imgui handles this font but cimgui does not.
