### ISSUE TITLE
structs: why are they `uintptr`s?

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#147]
We made most of our types `type TypeName uintptr`. I think it was a simplification (to make generator easier), but now we could improve it, couldn't we?
We can do it like we do with functions - we can use existing type/return wrappers to generate working `handle()` methods.
Any thoughts?

**Comment by AllenDang** [comment]
@gucio321 Totally agreed

**Comment by gucio321** [comment]
@AllenDang we need naming convention, especially:
- what if field has `_` on beginning? My proposal is to remove or replace with "internal"
- what if field name duplicates with method name? (maybe add `Field` prefix?
