### ISSUE TITLE
backend: CreateBackend should not depend on glfw backend implementation

### ISSUE THREAD

**Issue by ptxmac** [AllenDang/cimgui-go#153]
The glfw backend is supposed to be removed if `exclude_cimgui_glfw` is set as a build tag. Unfortunately `backend.go` is depending on the `GLFWBackend` type, so setting the build tag just means the package won't compile any more

**Comment by gucio321** [comment]
well, yeah, I think it is expected for now, since we don't have any other backend (refer #41)

**Comment by gucio321** [comment]
oh ok, I see what you mean:
```go
func CreateBackend( /*TODO: backend type*/ ) Backend {
        currentBackend = &GLFWBackend{}
        return currentBackend
}
```

refering to this TODO: we need to completly remove this GLFWBackend dependency from there, since it should be an argument to this function.

**Comment by ptxmac** [comment]
Exactly, I think this is related to the discussion in #41 

(I just noticed you reopened it)

As a side-note, I have a glfw backend implemented without any c code here: https://github.com/ptxmac/cimgui-go-examples

**Comment by gucio321** [comment]
> As a side-note, I have a glfw backend implemented without any c code here: https://github.com/ptxmac/cimgui-go-examples

great to hear!

> Exactly, I think this is related to the discussion in https://github.com/AllenDang/cimgui-go/issues/41
> 
> (I just noticed you reopened it)

ok, so lets close this ant move further duscussion to #41

**Comment by gucio321** [comment]
oh nevermind, I've just read the title (which I set by my own :smile:).
Leave this better open for now

**Comment by kschamplin** [comment]
perhaps we should take the approach of `sql` and use a "drivers" list . We can then write something like this:
```go
import (
    imgui "github.com/AllenDang/cimgui-go"
    _ "github.com/AllenDang/cimgui-go/glfwbackend"
)

func main() {
    backend = imgui.CreateBackend("glfw") // other backends would use different identifiers
    // rest of code...
}
```

**Comment by gucio321** [comment]
Give me a moment, ill do that
