### ISSUE TITLE
how to access  ImGuiTableSortSpecs->Specs[n]  ?

### ISSUE THREAD

**Issue by keepstep** [AllenDang/cimgui-go#160]
how to access  ImGuiTableSortSpecs->Specs[n]  ?

defined in  imgui :
```c++
struct ImGuiTableSortSpecs
{
    const ImGuiTableColumnSortSpecs* Specs;     // Pointer to sort spec array.
    int                         SpecsCount;     // Sort spec count. Most often 1. May be > 1 when ImGuiTableFlags_SortMulti is enabled. May be == 0 when ImGuiTableFlags_SortTristate is enabled.
    bool                        SpecsDirty;     // Set to true when specs have changed since last time! Use this to sort again, then clear the flag.

    ImGuiTableSortSpecs()       { memset(this, 0, sizeof(*this)); }
};
```

**Comment by gucio321** [comment]
See #151

**Comment by gucio321** [comment]
well, my PR says:
```console
2023-07-22 11:08:01	[FAIL]:	(gengo_structs.go:141):	Cannot generate struct "ImGuiTableSortSpecs", because its member Specs is of unsupported type const ImGuiTableColumnSortSpecs*
```

**Comment by AllenDang** [comment]
I'd say, we don't need to use ImGuiTableSortSpecs, instead of it, we should sort go array directly to archive same results.

**Comment by keepstep** [comment]
It is valuable for me ,the  project is a db access  tool, according table column specs ,generate sql ,then get data.

**Comment by keepstep** [comment]
I will be very glad and thanksful If you can support it

**Comment by AllenDang** [comment]
Why can you just use golang to sort the data you read from db?

**Comment by keepstep** [comment]
Oh, I mean,  click header to gen a sorting sql , eg:  ...order by id desc/asc .

Let db to do sorting.

Golang do not sort data.

**Comment by keepstep** [comment]
Yes it is.  
In c++ ,Specs[i] has already record user click defaultly ,
three kind of sort state: none,asc,desc.

if it is accssable in golang, I  just need to read the Specs  to combine  sql , 
That will be convience

**Comment by AllenDang** [comment]
The reason why I didn't implement sort spec is, to pass huge data between C++ and Go will involve huge performance lag, current implementation only pass data from Go -> C++, with sort spec the data flow will be Go -> C++ -> Go, so to avoid performance overhead, I decide not to use sort spec.

**Comment by keepstep** [comment]
thank you for your explanation ， i know that you are standing your principle that performance is most important。
however i think full-feature supporting is also important， and the performance lag only happens when using this feature。Also there is some ways to avoid it，example：i can cache the specs data in golang vars and do not to call getSpecs per frame。
Anyway，thanks for your project

**Comment by gucio321** [comment]
Generally nor sure wht this getter/setter doesn't wxist. Gonna investigate this

**Comment by gucio321** [comment]
@keepstep it is absolutly possible in the latest code.
There is a wrapped struct:
```go
type TableSortSpecs struct {
        FieldSpecs      *TableColumnSortSpecs // Pointer to sort 
        FieldSpecsCount int32                 // Sort spec count.
        FieldSpecsDirty bool                  // Set to true when
}
```
The only thing you need to do is convert *TableColumnSortSpecs to a go slice (shouldn't be very difficult)
Or you can use auto-generated accessor
```go
func (self TableSortSpecs) SetSpecs(v *TableColumnSortSpecs) {
        vArg, vFin := v.handle()

        selfArg, selfFin := self.handle()
        defer selfFin()
        C.wrap_ImGuiTableSortSpecs_SetSpecs(selfArg, vArg)

        vFin()
}

func (self *TableSortSpecs) Specs() *TableColumnSortSpecs {
        selfArg, selfFin := self.handle()

        defer func() {
                selfFin()
        }()
        return newTableColumnSortSpecsFromC(C.wrap_ImGuiTableSortSpecs_GetSpecs(selfArg))
}
```

**Comment by gucio321** [comment]
some example of converting pointer to slice:
```go
package main

import (
    "fmt"
    "unsafe"
)

func main() {
    // Assuming you have a pointer to an int array and you know the length
    ptr := &([]int{1, 2, 3, 4, 5}[0]) // Pointer to the first element of the array
    length := 5 // Length of the slice

    // Convert the pointer to a slice
    slice := (*[1<<30]int)(unsafe.Pointer(ptr))[:length:length]

    // Now you have a slice pointing to the same data as the pointer
    fmt.Println(slice)
}
```

**Comment by runrc** [comment]
As discussed with @gucio321 on [Discord](https://discord.com/channels/1306199225616306248/1306240998967476316/1356547749868212256)

The solution is to convert the pointer to the underlying to a slice. Here is an example of how to extract SortSpec to a slice to enable multi-column sorting for a table.

```go
func PtrToSlice[T any](x *T, length int) []T {
    if x == nil || length <= 0 {
        return nil
    }
    return unsafe.Slice(x, length)
}

...

sortSpecs := imgui.TableGetSortSpecs()

if sortSpecs.SpecsDirty() {
   len := int(sortSpecs.SpecsCount())
   slice := PtrToSlice(sortSpecs.Specs().CData, len)

   // Sort your data here.

   sortSpecs.SetSpecsDirty(false)
}

```
