### ISSUE TITLE
Simple Example Segmentation Fault; Windows / TDM-GCC

### ISSUE THREAD

**Issue by michaelquigley** [AllenDang/cimgui-go#162]
I've got a simple example:

```
package main

import (
	imgui "github.com/AllenDang/cimgui-go"
)

func loop() {
	imgui.Begin("Surface")
	imgui.TextUnformatted("Hello World")
	imgui.End()
}

func main() {
	backend := imgui.CreateBackend(imgui.NewGLFWBackend())
	backend.CreateWindow("Surface App", 1200, 900, 0)
	backend.Run(loop)
}
```

When I build and run this using go 1.20.4, and TDM-GCC 10.3.0, I get a working application. If I then grab the lower right corner and change the size of the GLFW window, I get a segmentation fault every time on Windows.

Running it in `gdb` doesn't really net anything useful:

```
[New Thread 23036.0x6f48]
[New Thread 23036.0x3d60]
[New Thread 23036.0x37a8]
[New Thread 23036.0x6ea0]
[New Thread 23036.0x8a24]
[New Thread 23036.0x34b8]
[New Thread 23036.0x4908]
[New Thread 23036.0x71cc]
[New Thread 23036.0x5f00]
[New Thread 23036.0x3978]
[New Thread 23036.0x41e0]
warning: Error 20 (this feature has not been implemented yet) in function AVolute::GetProductInfoT::<lambda_3920e95365a48b95dd51020986e9e351>::operator ()
warning: Error 20 (this feature has not been implemented yet) in function AVolute::GetProductInfoT::<lambda_3920e95365a48b95dd51020986e9e351>::operator ()
warning: Error 20 (this feature has not been implemented yet) in function AVolute::GetProductInfoT::<lambda_3920e95365a48b95dd51020986e9e351>::operator ()
warning: Error 20 (this feature has not been implemented yet) in function AVolute::GetProductInfoT::<lambda_3920e95365a48b95dd51020986e9e351>::operator ()
warning: Error 20 (this feature has not been implemented yet) in function AVolute::GetProductInfoT::<lambda_3920e95365a48b95dd51020986e9e351>::operator ()
warning: Error 20 (this feature has not been implemented yet) in function AVolute::GetProductInfoT::<lambda_3920e95365a48b95dd51020986e9e351>::operator ()
[New Thread 23036.0x168]
[New Thread 23036.0x5bd4]
[New Thread 23036.0x8a70]
[Thread 23036.0x168 exited with code 0]
[Thread 23036.0x5bd4 exited with code 0]
[Thread 23036.0x8a70 exited with code 0]
[New Thread 23036.0x83e0]
[New Thread 23036.0x58d8]
[New Thread 23036.0x6e24]
[New Thread 23036.0x4314]
[New Thread 23036.0x7fdc]
[Thread 23036.0x7fdc exited with code 0]

Thread 16 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 23036.0x83e0]
0x000002506c85fe2e in ?? ()
(gdb) bt
#0  0x000002506c85fe2e in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Any advice on how to troubleshoot this would be appreciated.

**Comment by michaelquigley** [comment]
Interestingly... If i grab the lower right corner, which allows me to change the height and width at the same time, this will result in a segmentation fault. If I grab the right edge or the bottom edge, and only adjust the width or the height separately, I don't get a segmentation fault.

**Comment by michaelquigley** [comment]
Also, if I grab the lower right corner and move it very, very slowly, it will not segfault. If I move it more rapidly, that's when the issue occurs.

**Comment by michaelquigley** [comment]
Grabbed a quick screen capture:
![segfault](https://github.com/AllenDang/cimgui-go/assets/4443091/e1ed016e-fef1-4f29-9c4e-12c82e80b36f)

**Comment by gucio321** [comment]
Its very strange. I think it is related to something inside glfw, because on linux it works.
Can you check if [Dear ImGui](https://github.com/ocornut/imgui) with glfw backend also crashes?

**Comment by michaelquigley** [comment]
I've been using Dear ImGui with a GLFW backend on Windows through C++ for years without issues. And this does not happen on Linux builds for me, either.

**Comment by michaelquigley** [comment]
I used the same TDM-GCC toolchain along with a GLFW 3.3.8 build for 64-bit mingw to produce this... works fine with plain ImGui... There's something going on with `cimgui-go` that's causing an issue.

![plain_imgui](https://github.com/AllenDang/cimgui-go/assets/4443091/de49fb94-dc17-4fa9-8ba7-c04d828caa07)

I'll also try and dig into the GLFW wrapper a little and see if I can figure out what's going on.

**Comment by gucio321** [comment]
@michaelquigley chould you try now? debugging should be easier after #173

**Comment by gucio321** [comment]
deprecated (let me know if it still crashes on latest master)
