### ISSUE TITLE
How can i use ImGuiWindowFlags?

### ISSUE THREAD

**Issue by hexvalid** [AllenDang/cimgui-go#17]
Hello,
Where do i put my ImGuiWindowFlags like `ImGuiWindowFlags_NoResize`, `ImGuiWindowFlags_NoTitleBar` or `ImGuiWindowFlags_NoCollapse`?

I tried here but no luck:
` cimgui.CreateGlfwWindow("Hello from cimgui-go", 1200, 900, cimgui.ImGuiWindowFlags_NoResize)`

Thanks

**Comment by AllenDang** [comment]
@hexvalid CreateGlfwWindow is creating a OS window, not imgui's window.

**Comment by hexvalid** [comment]
So, i can't access imgui's window properties with this API. I see flags are hardcoded here:
https://github.com/AllenDang/cimgui-go/blob/f683fbf0e44e06806f2f77d1cedf78eea6a06f93/backend.cpp#L102-L107

**Comment by AllenDang** [comment]
@hexvalid That's the config flag for IO, what you need is simply `cimgui.BeginV("WIndow title", is_opened, what_ever_window_flags_you_need)`

**Comment by hexvalid** [comment]
OK, I misunderstood. I got it with `cimgui.BeginV`. Also i can modify config flags with `cimgui.GetIO().SetConfigFlags`.
Perfect.
