### ISSUE TITLE
Broken SetMergeMode in fonts (last PR)

### ISSUE THREAD

**Issue by Wolf65** [AllenDang/cimgui-go#171]
After the last PR broken the function in FontConfig SetMergeMode crashes with "exit status 0xc0000005" although everything was fine before.  And still also set glyph range doesn't work and I have to use 
Ranges = []uint16{0x0020, 0xA69F, 0}
ioF.Fonts().AddFontFromFileTTFV("fonts/ttf/JetBrainsMono-Medium.ttf", baseFontSize, fontFa, (*imgui.Wchar)(unsafe.Pointer(&Ranges[0]))))

**Comment by gucio321** [comment]
@Wolf65 can you post some reproduction code pls

**Comment by Wolf65** [comment]
https://github.com/Wolf65/PoEHelper/blob/main/fonts/Utilit.go


Unfortunately, I do not have a PC and can only link to the file from the repository (the code is not updated for the latest changes in line 38 will error on 0 which should be replaced by fontConfig).

**Comment by Wolf65** [comment]
Will hastily find a commit where SetMegreMode v0.0.0.0-20230619023324-e4dae85333e0 is running. Unfortunately there is no way to find the exact commit where the bug occurs.

**Comment by Wolf65** [comment]
https://github.com/Wolf65/Bug

Made a minimal project with reproduction of the error. In go.mod commits on which everything works and the last one.

**Comment by gucio321** [comment]
@Wolf65 I'm on 218b711492995ee988bd6727b8712392b3816be6 and your code works for me when I put it in examples/ folder inside of this repo

**Comment by gucio321** [comment]
ok, finally I managed to debug this correctly (see #172)
```console
File: imgui_draw.cpp, Line: 2083
```
so:
```c++
    // Create new font
    if (!font_cfg->MergeMode)
        Fonts.push_back(IM_NEW(ImFont));
    else
        IM_ASSERT(!Fonts.empty() && "Cannot use MergeMode for the first font"); // <- this one
```
SO
AddFont seems to fail adding font

**Comment by gucio321** [comment]
```go
func (self FontAtlas) AddFontFromMemoryTTFV(font_data unsafe.Pointer, font_size int32, size_pixels float32, font_cfg FontConfig, glyph_ranges *Wchar) Font {
	selfArg, selfFin := self.handle()
	font_cfgArg, font_cfgFin := font_cfg.handle()

	defer func() {
		selfFin()
		font_cfgFin()
	}()
	return newFontFromC(*C.ImFontAtlas_AddFontFromMemoryTTF(selfArg, (font_data), C.int(font_size), C.float(size_pixels), font_cfgArg, (*C.ImWchar)(glyph_ranges)))
}
```
I suppose that there is something wrong with this finalizer?
Lets compare with the working one:
```go
func (self FontAtlas) AddFontFromMemoryTTFV(font_data unsafe.Pointer, font_size int32, size_pixels float32, font_cfg FontConfig, glyph_ranges *Wchar) Font {
        return (Font)(unsafe.Pointer(C.ImFontAtlas_AddFontFromMemoryTTF(self.handle(), (font_data), C.int(font_size), C.float(size_pixels), font_cfg.handle(), (*C.ImWchar)(glyph_ranges))))
}
```

**Comment by gucio321** [comment]
ok, very important experiment:
```go
	fmt.Println(io.Fonts())
	fmt.Println(io.Fonts())
	fmt.Println(io.Fonts())
```
this one used to return the same value three times, now it doesn't

**Comment by gucio321** [comment]
_I suppose that I found the problem_
```go
func newFontAtlasFromC(cvalue C.ImFontAtlas) FontAtlas {
	result := new(FontAtlas)
	result.data = unsafe.Pointer(&cvalue) // <-
	return *result
}
```
so it looks like in our workflow C pointer gets dereferenced and then we create another pointer
So its a bug

**Comment by Wolf65** [comment]
This is awesome. I didn't expect such a deeply closed problem that led to improved debugging tools.By the way maybe this will fix imgui.ini

**Comment by gucio321** [comment]
maybe, we can check

**Comment by Wolf65** [comment]
Checked. All SetMergeMode works as it should. imgui.ini unfortunately this fix didn't help, it is still not created.
