### ISSUE TITLE
IM_ASSERT

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#172]
Hi there!
When `IM_ASSERT` throws an error it arrives to go as some really strange-looking `segmentation fault` panic that is completely undebuggable.
I've discovered a way to make it a bit cleaner.
there is an `imconfig.h` file that allows to define our own implementation of `IM_ASSERT` and we can do something like this:
```C++
//---- Define assertion handler. Defaults to calling assert().
// If your macro uses multiple statements, make sure is enclosed in a 'do { .. } while (0)' block so it can be used as a single statement.
#define IM_ASSERT(_EXPR)  MyAssert(_EXPR, __FILE__, __LINE__)
//#define IM_ASSERT(_EXPR)  ((void)(_EXPR))     // Disable asserts
//
#include <stdio.h>
#include <stdlib.h>
static void MyAssert(bool cond/*const char *expr*/, const char *file, int line) {
        if (cond) {
                return;
        }
    FILE *log_file = fopen("error.log", "a");
    if (log_file) {
        //fprintf(log_file, "Error in expression: %s\n", expr);
        fprintf(log_file, "File: %s, Line: %d\n", file, line);
        fclose(log_file);
    }

    //fprintf(stdout, "Error in expression: %s\n", expr);
    fprintf(stdout, "File: %s, Line: %d\n", file, line);

    // Instead of throwing an exception, we're using exit(1) to terminate the program.
    exit(1);
}
```
(this is a prototype that needs to be improved)
But it returns some _human readable_ output - file and line number when the exception happens.
@AllenDang any thoughts :smile:
Also I need some C++ help in order to make this function better :grinning:

**Comment by gucio321** [comment]
I think we can remove this log file. It was in case stdout was broken somehow, but it works so we don't need to create this file

**Comment by gucio321** [comment]
Also, I can do like this:
```C++
#ifdef CIMGUI_GO_DEBUG
#define IM_ASSERT(_EXPR)  MyAssert(_EXPR, __FILE__, __LINE__)
#include <stdio.h>
#include <stdlib.h>
static void MyAssert(bool cond, const char *file, int line) {
        if (cond) {
                return;
        }

    fprintf(stdout, "File: %s, Line: %d\n", file, line);

    // Instead of throwing an exception, we're using exit(1) to terminate the program.
    exit(1);
}
#endif
```

and then in GO:
```go
package cimgui
//go:build debug
//+build debug

//#cgo CPPFLAGS: -DCIMGUI_GO_DEBUG
import "C"
```
and when building with `debug` tag my function will be enabled

**Comment by AllenDang** [comment]
Cool

**Comment by gucio321** [comment]
well, I think I know whats the problem. In go we're using pre-built imgui binaries and preprocessor directives are not considered while generating go binary
