### ISSUE TITLE
Incorrect data type in imgui.Wchar

### ISSUE THREAD

**Issue by Wolf65** [AllenDang/cimgui-go#175]
In "extra_types.go" "Wchar" has data type "C.uint"
By default in imgui "typedef ImWchar16 ImWchar" 
with "IMGUI_USE_WCHAR32" flag "typedef ImWchar32 ImWchar".

and with current data types to pass the font range you should use
```
Ranges = []uint16{0x0020, 0xA69F, 0}
io.Fonts().AddFontFromFileTTFV("fonts/ttf/JetBrainsMono-Medium.ttf",
		baseFontSize,
		jetBrainsConfig,
		(*imgui.Wchar)(unsafe.Pointer(&Ranges[0])))))
```

correct usage

```
Ranges = []imgui.Wchar{0x0020, 0xA69F, 0}
io.Fonts().AddFontFromFileTTFV("fonts/ttf/JetBrainsMono-Medium.ttf",
		baseFontSize,
		jetBrainsConfig,
		&Ranges[0])

```
and it looks like "IMGUI_USE_WCHAR32" is not applied and "golang" expects the flag to be applied.

**Comment by Wolf65** [comment]
And for playback, https://github.com/Wolf65/Bug is fine with minor modifications

**Comment by gucio321** [comment]
@Wolf65 from cimgui/cimgui.h
```h
typedef unsigned short ImWchar16;
typedef unsigned int ImWchar32;typedef ImWchar32 ImWchar;
```
so C.uint seems to be good

**Comment by Wolf65** [comment]
Yes uint on the golang side is correct and should be unit
Golang imgui.wchar (32bit)
But in the current C++ imgui wchar (16bit) configuration, most likely, the flag for 32 bits is not applied, so the range data are passed incorrectly. And the range is set incorrectly.

**Comment by gucio321** [comment]
oh, so we need to pass `-DIMGUI_USE_WCHAR32` somewhere right?

**Comment by Wolf65** [comment]
Yeah. That flag is in https://github.com/AllenDang/cimgui-go/blob/606eb8908b6c3960a39b2c26cba733fc51014d45/Makefile#L65

**Comment by gucio321** [comment]
yeah, its also there: https://github.com/AllenDang/cimgui-go/blob/606eb8908b6c3960a39b2c26cba733fc51014d45/lib/CMakeLists.txt#L29

And I've just added it there: https://github.com/gucio321/cimgui-go/blob/cf12e5273f821744e0ef075ebca0e76738bc87d6/cimgui.go#L3

but it doesn't seem to help

**Comment by Wolf65** [comment]
If I understand correctly, this flag should also be set in the 
`cimgui-go/.github/workflows/build-lib-*.yml`

**Comment by gucio321** [comment]
oh got it. Its because of my cmake missknownladge :smile:
I tried to use `set(IMGUI_USE_WCHAR32)` but it should be `add_definition(IMGUI_USE_WCHAR32)` :smile:

**Comment by gucio321** [comment]
opening a PR containing this change along with some codegen improvements

**Comment by Wolf65** [comment]
Strange just updated to the latest commit imgui.Wchar still works only through (*imgui.Wchar)(unsafe.Pointer(&IconRange[0])) can this be due to the fact that in cimgui-go/lib windows/x64 lask commit - last week and the rest 2 days ago.

crashes with the message "exit status 0xc0000005" error.log is empty

**Comment by gucio321** [comment]
`(*imgui.Wchar)(unsafe.Pointer(&IconRange[0]))`
@Wolf65 this isn't fixed yet. Its because it is really hard to determine whtere C pointer should be go slice or go pointer. IIRC there is a dedicated issue

**Comment by Wolf65** [comment]
@gucio321 I apologize for misreading the PR.

**Comment by gucio321** [comment]
no problem

**Comment by gucio321** [comment]
@Wolf65 I've added a workaround function: https://github.com/AllenDang/cimgui-go/pull/179

**Comment by Wolf65** [comment]
Correct me if I'm wrong at the moment :

current working code:
```
Ranges = []uint16{0x0020, 0xA69F, 0}
io.Fonts().AddFontFromFileTTFV("fonts/ttf/JetBrainsMono-Medium.ttf",
		baseFontSize,
		jetBrainsConfig,
		(*imgui.Wchar)(unsafe.Pointer(imgui.SliceToPtr(Ranges))))
```

But the correct variant when IMGUI_USE_WCHAR32 flag:
```
Ranges = []imgui.Wchar{0x0020, 0xA69F, 0}
io.Fonts().AddFontFromFileTTFV("fonts/ttf/JetBrainsMono-Medium.ttf",
		baseFontSize,
		jetBrainsConfig,
		imgui.SliceToPtr(Ranges))
```

and this variant crashes and it turns out that the IMGUI_USE_WCHAR32 flag is not applied. Although there are commits in PR that add this flag. Or I need to specify this flag in go at run/build.

**Comment by gucio321** [comment]
It should work and works for me on linux

**Comment by gucio321** [comment]
Maybe try to run/build with -a flag

**Comment by Wolf65** [comment]
I think this is due to the fact that libs for windows were updated a week ago and for mac and linux 3 days ago. In my fork also windows action worked without errors but did not commit, but on linux and mac all worked and committed.

**Comment by gucio321** [comment]
Interessting i thought that i ran all 3 workflows but i had to miss windows

**Comment by gucio321** [comment]
@Wolf65 check now

**Comment by Wolf65** [comment]
Yeah, now it's working as intended.
