### ISSUE TITLE
ImGuiInputTextCallbackData.GetEventKey() always returns 0.

### ISSUE THREAD

**Issue by hexvalid** [AllenDang/cimgui-go#19]
Hi, i can't get last pressed char with this function. Returns always 0.

```
...
cimgui.InputTextWithHint("##label1", "", &var1, cimgui.ImGuiInputTextFlags_CallbackEdit, callback)
...

func callback(data cimgui.ImGuiInputTextCallbackData) int {
	fmt.Println(data.GetEventKey())
	return 0
}
```

**Comment by gucio321** [comment]
@hexvalid got it. It is just no timplemented yet.
https://github.com/AllenDang/cimgui-go/blob/5d9a1f0b1f727e23d05bc0ecb1f381d548b21c34/cmd/codegen/arg_wrapper.go#L317

**Comment by gucio321** [comment]
@AllenDang how should we do that?
maybe something similar to https://github.com/inkyblackness/imgui-go/blob/main/InputTextCallbackData.go

**Comment by AllenDang** [comment]
@gucio321 I already implemented it, check `input_text.go`, may need to fix some issue in there.

**Comment by gucio321** [comment]
@hexvalid _a bit late but I figured it out finally_
This is not a bug. This behaviour is caused by the way Dear ImGui works.
ref imgui.h:
```c
    ImWchar             EventChar;      // Character input                      // Read-write   // [CharFilter] Replace character with another one, or set to zero to drop. return 1 is equivalent to setting EventChar=0;
    ImGuiKey            EventKey;       // Key pressed (Up/Down/TAB)            // Read-only    // [Completion,History]
```
SO, If you have default flags set, only the `InputTextFlagsCallbackResize` is active AND `EventKey` will be 0. You need to set this flag in order to detect this kind of event and get callback.
