### ISSUE TITLE
Naming conventions?

### ISSUE THREAD

**Issue by eliasdaler** [AllenDang/cimgui-go#20]
Hello, I have a proposal.
The readme says:

> For functions, 'Im/ImGui/ig' is trimmed. 'GetCursorPos' is renamed to 'GetDrawCursor', same with "SetCursor...".

Maybe  we should do the same for various enums/constants/flags and even types as well? For example:

```go
cimgui.ImGuiKey_Tab // before
cimgui.Key_Tab // after
cimgui.KeyTab // even better!
```

```go
cimgui.ImGuiWindowFlags_NoCollapse // before
cimgui.WindowFlags_NoCollapse // after
cimgui.WindowFlagsNoCollapse // even better!
```

```go
cimgui.ImVec2 // before
cimgui.Vec2 // after
```

and so on... If you agree, I can do the work and later submit the PR.

**P.S.** And another question - why is the package named cimgui, not imgui? I feel like naming it "imgui" will make end-user experience better, for example you could call `imgui.Text` instead of `cimgui.Text` and so on. I know that you can import cimgui-go as "imgui" and do the same, but it's better to be convenient for user by default, imo.

Also see [imgui-rs](https://github.com/imgui-rs/imgui-rs) as the example. It uses cimgui as well, but doesn't call itself "imgui", because after all the end user is more interested in "imgui" part more than "cimgui" part.

**Comment by AllenDang** [comment]
For the naming conventions, I agree with you, shorter is better.
And for the package name, yes, it could be "imgui", glad to have a PR to change it

**Comment by eliasdaler** [comment]
Okay, I'll get to it after I figure out how the whole generation process works and submit some other more important PRs to help the transition from imgui-go for me.
