### ISSUE TITLE
Disabling/hiding platform window

### ISSUE THREAD

**Issue by maxsupermanhd** [AllenDang/cimgui-go#209]
I seen multiple projects that implemented main window as actual internal window (not platform one), however I am struggling with finding examples of such application.

Is it possible to not spawn system window and directly begin with the Dear ImGui windows in this binding?

**Comment by gucio321** [comment]
Hi!
What you are looking for is `imgui.WindowFlagsTransparent` (or other GLFWWindowFlags).
Use it in `CreateWindow` call.

**Comment by Wolf65** [comment]
It'll be a little crunched up since it's not at the pc.

Through backend.windowHint put GLFW_VISIBLE flag to false it will disable glfw window and it will not be visible in the system

Then create a window of any size via backend.CreateWindow and it will not be visible anyway.

imgui.CurrentIO().SetConfigViewportsNoAutoMerge(true)
This is mandatory so that imgui child windows do not "stick" to the hidden window glfw the tractors that will be in the area of the parent window will also be hidden.

**Comment by Wolf65** [comment]
@gucio321 I haven't dug much into windows hint yet, but I couldn't get the necessary keys to be passed there via int.

**Comment by Wolf65** [comment]
@gucio321 I checked the hint doesn't work.

**Comment by AllenDang** [comment]
For my understanding, the goal here is to create a borderless window (no platform title bar and border) right? 
There are a example in giu about how to implement one.
https://github.com/AllenDang/giu/blob/master/examples/transparent/transparent.go

The main code is `wnd := g.NewMasterWindow("transparent", 300, 200, g.MasterWindowFlagsNotResizable|g.MasterWindowFlagsFloating|g.MasterWindowFlagsFrameless|g.MasterWindowFlagsTransparent)`

**Comment by gucio321** [comment]
@AllenDang but applying these flags seems to have no expected effect.
see this:
```diff
diff --git a/examples/main.go b/examples/main.go
index 3885c53..c14cb66 100644
--- a/examples/main.go
+++ b/examples/main.go
@@ -126,7 +126,12 @@ func main() {
 
 	backend.SetBgColor(imgui.NewVec4(0.45, 0.55, 0.6, 1.0))
 
-	backend.CreateWindow("Hello from cimgui-go", 1200, 900, 0)
+	backend.CreateWindow("Hello from cimgui-go", 1200, 900,
+		imgui.GLFWWindowFlagsNotResizable|
+			imgui.GLFWWindowFlagsFloating|
+			imgui.GLFWWindowFlagsFrameless|
+			imgui.GLFWWindowFlagsTransparent,
+	)
 
 	backend.SetDropCallback(func(p []string) {
 		fmt.Printf("drop triggered: %v", p)
```

And the result doesn't differ from default behavior too much

![image](https://github.com/AllenDang/cimgui-go/assets/73652197/4b661016-ce40-4ab9-8274-f556e694d1fe)


The only change is that the window (MasterWindow) is always on top

**Comment by gucio321** [comment]
@maxsupermanhd btw, you can set `SetBgColor` wiht alpha = 0, but the window will still have decoration

**Comment by AllenDang** [comment]
Maybe this has something to do with the viewport feature, since those flag works in giu

**Comment by gucio321** [comment]
@AllenDang they do with imgui-go but doesn't with cimgui-go (I've checked transparent example on migration branch and it is broken)
Also I think it has nothing to do with viewport since these flags apply to GLFW so viewport has nothing to do with it, does it?

**Comment by AllenDang** [comment]
@gucio321 I think I know why, the Flags should map to GLFW's definition, currently they are defined with fixed value.

Here is current definition
```go
typedef int GLFWWindowFlags;
enum GLFWWindowFlags_ {
  GLFWWindowFlagsNone = 0,
  GLFWWindowFlagsNotResizable = 1 << 0,
  GLFWWindowFlagsMaximized = 1 << 1,
  GLFWWindowFlagsFloating = 1 << 2,
  GLFWWindowFlagsFrameless = 1 << 3,
  GLFWWindowFlagsTransparent = 1 << 4,
};
```

which should change to 
```go
typedef int GLFWWindowFlags;
enum GLFWWindowFlags_ {
  GLFWWindowFlagsFloating = C.GLFW_FLOATING
};

```

**Comment by gucio321** [comment]
@AllenDang no, it doesn't matter because in the code, these flags are translated later.
Look on this one:
```c
  if ((flags & GLFWWindowFlagsNotResizable) != 0) {
    glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);
  }

  if ((flags & GLFWWindowFlagsMaximized) != 0) {
    glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE);
  }

  if ((flags & GLFWWindowFlagsFloating) != 0) {
    glfwWindowHint(GLFW_FLOATING, GLFW_TRUE);
  }

  if ((flags & GLFWWindowFlagsFrameless) != 0) {
    glfwWindowHint(GLFW_FLOATING, GLFW_TRUE);
  }

  if ((flags & GLFWWindowFlagsTransparent) != 0) {
    glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);
  }
```
code from igCreateGLFWWindow

so the value of GLFWWindowFlagsXXX doesn't matter as long as we use this method to apply them

**Comment by AllenDang** [comment]
@gucio321 I see, I misunderstood that, that's strange, if that so, those flags should work...

**Comment by Wolf65** [comment]
Then try my method of hiding via visible and noautomerge

**Comment by maxsupermanhd** [comment]
> Then try my method of hiding via visible and noautomerge

It does not work, noautomerge works and spawn windows separate from main one but making main go away right now is impossible as I understood

**Comment by Wolf65** [comment]
It's just that I'm still in fork locally specified this flag in backend.go and haven't tried it via windowhint

**Comment by gucio321** [comment]
Got it!
We experience two separated problems here:
- first of all we need to set `GLFW_DECORATED` to `false` (and this is not exported to cimgui-go)
- Second problem is that `GLFW_TRANSPARENT_FRAMEBUFFER` conflicts with `glfwClearColor` (which is called arbitrarly by our code implementation).

so to fix this we need to:
- export `GLFW_DECORATED` hint
- fix code to check if `GLFW_TRANSPARENT_FRAMEBUFFER` flag is set before calling clearColor OR set clear color to color with 0 on alpha channel

**Comment by Wolf65** [comment]
@maxsupermanhd 
You can check the flags have been added. Note on examples/main.go that the backend initialization has changed a bit.

backend.SetWindowFlags(imgui.GLFWWindowFlagsVisible, 0)
...
backend.CreateWindow(config.App.Info.ProjectName, 500, 500)
...
imgui.CurrentIO().SetConfigViewportsNoAutoMerge(true)
