### ISSUE TITLE
Convenience functions with sensible defaults

### ISSUE THREAD

**Issue by eliasdaler** [AllenDang/cimgui-go#21]
Hello, I've recently encountered this #9 after not finding `imgui.InputText` anywhere. Of course, I can make something like this:

```go
func InputText(label string, buf *string) bool {
	return imgui.InputTextWithHint(label, "", buf, 0, nil)
}
```

... but wouldn't it be convenient to have this in cimgui-go for many others as well? 

Same goes for not having `cimgui.Image` and using `cimgui.ImageV` instead and so on.

So, what's your opinion on adding various helpers like that? [imgui-go](https://github.com/inkyblackness/imgui-go) had lots of them and it made writing Dear ImGui code in Go as good as in C++ if not better.

**Comment by AllenDang** [comment]
I think convenient functions are good to have, :)

**Comment by eliasdaler** [comment]
Are there any wrappers like this already? The ones which are not generated by codegen. I just want to know what's the best place for them.

**Comment by gucio321** [comment]
There is inkyblackness/imgui-go

**Comment by eliasdaler** [comment]
@gucio321, it won't be maintained anymore: https://github.com/inkyblackness/imgui-go/discussions/192

**Comment by gucio321** [comment]
hmm, shouldn't `input_text.go` be auto-generated? I suppose it isn't now, does it? https://github.com/AllenDang/cimgui-go/blob/main/input_text.go

**Comment by AllenDang** [comment]
@gucio321 There are lots of stuff need to manual process for input text.

**Comment by gucio321** [comment]
I suppose this is done. `gencpp.go` already adds another function if there are defaults declared in json.
