### ISSUE TITLE
Reasons for using "just" build system?

### ISSUE THREAD

**Issue by eliasdaler** [AllenDang/cimgui-go#22]
Hello again.
I was wondering why "just" was used as a build system. 
I see that GNU Make was previously used, so what are the reasons for going with a non-standard build system? (especially seeing how Makefile wasn't that complicated)

I also see that cimgui-go depends on CMake for building, so maybe it should go with it instead? (I can implement CMake build if you agree)

**Comment by AllenDang** [comment]
@eliasdaler "just" is more easy to understand, easy to write and easy to use. I'm using it more and more in my project.
For CMake, it's complicate, I don't quite understand it, just use it to do the cross-platform build...

**Comment by JetSetIlly** [comment]
I've not moved to cimgui-go yet and I've not kept up to speed with its development. Can you explain this build system a little more please.

In particular: If I migrate my project to cimgui-go and somebody wants to build it on their system will they have to have the just build system installed?

**Comment by AllenDang** [comment]
@JetSetIlly "just" is used to generate binding code, "cmake" is used to compile binary libs for macOS/win/linux.
For end user, all they need to do is just "go get ...".

**Comment by JetSetIlly** [comment]
Okay. That sounds reasonable. Thanks.

**Comment by eliasdaler** [comment]
My problems with "just" is that it's not present in most default Linux repos and not that easy to install for people who want to contribute (compared to CMake, which is a pretty much default way to build C++ things and is used during the build process anyways).

Closing for now, might come up with a PR showing how CMake build will look later. If you find it hard to understand, it's okay if you reject it. :)

**Comment by AllenDang** [comment]
@eliasdaler I see, I'm ok to go with 'CMake'. I'm not a linux user so I don't know "just" is not that easy to install. :P
