### ISSUE TITLE
Renaming of some functions? (e.g. GetCursor, SetCursor)

### ISSUE THREAD

**Issue by eliasdaler** [AllenDang/cimgui-go#23]
What are the reasons for renaming these two functions? While I understand that "GetDrawCursor" and "SetDrawCursor" are more descriptive, I think it'll be better to avoid as much renaming as possible because then it'll be easier for people to look at imgui_demo.cpp and other Dear ImGui code and be able to port it 1-to-1 without changing much of the naming in the process.

(Doesn't apply to what's discussed in #20 since package name will acts as "ImGui/Im" prefix and will be easy to map)

**Comment by AllenDang** [comment]
Simply because "GetCursor" and "SetCursor" are very misleading. I was asked countless times why this functions cannot set mouse cursor.
But, I agree with you, remain their original name should be more easy to learn from imgui's demo code.

**Comment by eliasdaler** [comment]
I see. So what's your opinion on this? Should it stay that way or should we get rid of it?

**Comment by AllenDang** [comment]
@eliasdaler I say get rid of it.
