### ISSUE TITLE
AcceptDragDropPayload can't be checked for nil

### ISSUE THREAD

**Issue by ptxmac** [AllenDang/cimgui-go#231]
`AcceptDragDropPayload` will return a "nil" Payload if the currently dragged item is not of the expected type. There's currently no way to check this.

Either `AcceptDragDropPayload` should return a nil object if the payload is nil, or the `Payload` type should have a way to check for nil

I.e. from the client code:

```go
if AcceptDragDropPayload("Node") != nil {
  // handle drop
}
```

OR

```go
if !AcceptDragDropPayload("Node").IsNil() {
  // handle drop
}
```

**Comment by ptxmac** [comment]
Confirmed as working! 🎉

**Comment by gucio321** [comment]
hreat to hear!
But I accidently removed Payload.Data()  :smile: - will fix soon

**Comment by ptxmac** [comment]
Yeah, that didn't work before for me anyway, so my local hack was just to keep drag data in a global variable 😄

**Comment by gucio321** [comment]
now should work
