### ISSUE TITLE
GLFW backend not rendering, when there are no events

### ISSUE THREAD

**Issue by wildangelcult** [AllenDang/cimgui-go#234]
After implementing real time plotting in my code, I noticed that the plot doesn't update, when I don't move the mouse.

I did some debugging and found this piece of code in glfw_backend.cpp:
https://github.com/AllenDang/cimgui-go/blob/2be2c77051cfb58b153ace3305c0014bf34c8552/glfw_backend.cpp#L206
```c++
if (extra_frame_count > 0) {
	extra_frame_count--;
} else {
	glfwWaitEvents();
	extra_frame_count = MAX_EXTRA_FRAME_COUNT;
}
```

I have experimented with `glfwWaitEventsTimeout`, but I don't think there is a way to save the code above. I'm no graphics programmer, so you have to decide what is the best way to fix this.

But I think, that this just can't be there. There is no good reason to block an entire render thread and wait for inputs, that might not even come.

**Comment by AllenDang** [comment]
Just call `Refresh` of Backend to manual trigger the window to redraw.

**Comment by wildangelcult** [comment]
Thanks for the help, this works. The code is still a bit crazy though :D
