### ISSUE TITLE
adding cimgui-go as a dependency with go get does not compile

### ISSUE THREAD

**Issue by yvz5** [AllenDang/cimgui-go#238]
I have created a new go project and used the example main.go. then I ran CGO_ENABLED=1 go run . command but I got an error:
```bash
# github.com/AllenDang/cimgui-go
In file included from ./cimgui_structs_accessor.h:6,
                 from vendor/github.com/AllenDang/cimgui-go/cimgui_funcs.go:7:
./cimgui_wrapper.h:6:10: fatal error: cimgui/cimgui.h: No such file or directory
    6 | #include "cimgui/cimgui.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

weird part is when I clone this repo and go into examples folder and run the main.go file it works. What am I doing wrong ? How is this repo structured to be used from inside a go project ?

**Comment by gucio321** [comment]
Hi! First of all I have to say sorry for the late reply but I missed this issue somehow.
Error like this happens when using vendor mode (see #34 ). 
Inspite of I tought it was already fixed it turns out that it isn't. Let me reopen the other issue.
