### ISSUE TITLE
Idea: move implot functions to a separate package

### ISSUE THREAD

**Issue by eliasdaler** [AllenDang/cimgui-go#25]
Hello. When working on #20, I've noticed that some enum names can clash if we remove prefixes, e.g. ImAxis from implot and ImGuiAxis from Dear ImGui.

This got me thinking... what if we move all implot things to a directory called "implot" and call this package "implot as well"? This way, people would be able to do this:

```go
import "github.com/AllenDang/cimgui-go/implot"

// later in code
implot.SomeFunc()
```

and people who don't use implot won't get their autocomplete suggestions polluted by implot funcs/enums/structs if they don't want to use them.

**Comment by AllenDang** [comment]
Agree.

**Comment by SuperGod** [comment]
I think cgo will be a troublesome problem。
As far as I know, there will be problems when two packages using cgo link to the same static library

**Comment by eliasdaler** [comment]
I'll need to try this. But if that's a case, I'm a bit shocked that Go has this problem unresolved.

**Comment by gucio321** [comment]
Funfact about this:
`C.int` in one package isn't equal to `C.int` in the other...

**Comment by gucio321** [comment]
#232 moved C backends away from cimgui-go main package.
I think I'll try this for other things but at current moment can't promise anything
https://github.com/gucio321/cimgui-go/tree/split-packages
