### ISSUE TITLE
Some functions are renamed in latest commit

### ISSUE THREAD

**Issue by damntourists** [AllenDang/cimgui-go#262]
Hey there,

I just updated my cimgui-go and noticed that when compiling, certain functions got renamed. 

The following has changed for me:
```
imgui.IsMouseDoubleClicked => imgui.IsMouseDoubleClickedNil
imgui.IsMouseDown => imgui.IsMouseDownNil
```

is this something that should be fixed in the repo or is it possibly something with my local environment?

**Comment by gucio321** [comment]
git blame says: https://github.com/AllenDang/cimgui-go/pull/254/files#diff-7ef8e7ee142c009aa14b99b2b1fc30946fe3ded2de27cac5522c2da4b649cc2e

SO something in upstream changed

**Comment by gucio321** [comment]
This change seems to come from cimgui repo. I've asked them about it: https://github.com/cimgui/cimgui/issues/262

**Comment by gucio321** [comment]
I think, the rule we should add to our generator would be "if overload has _Nil, this suffix should be skipped"

**Comment by gucio321** [comment]
fixed in https://github.com/AllenDang/cimgui-go/pull/264
