### ISSUE TITLE
ImGui::InputText not supported

### ISSUE THREAD

**Issue by tommysalt** [AllenDang/cimgui-go#263]
I discovered that `InputText` is not supported:
```cpp
IMGUI_API bool          InputText(const char* label, char* buf, size_t buf_size, ImGuiInputTextFlags flags = 0, ImGuiInputTextCallback callback = NULL, void* user_data = NULL);
```
https://github.com/ocornut/imgui/blob/c6236699671b2e5f94481c051cd19afe00cda583/imgui.h#L601
Example C++ usecase:
```cpp
ImGui::InputText("password (clear)", password, IM_ARRAYSIZE(password));
```
Is there a reason for it? It seems to be one of the most important widgets.

**Comment by gucio321** [comment]
generally input text is a hard thing to wrap because it involves InputTextCallback which is a callback type. Callback types are a bit tricky in go/C (see #224 )

Currently InputText widget is only available in the form of manually wrapped function `InputTextWithHint`.

**Comment by gucio321** [comment]
spoiler: I'm working on this on a branch in my fork `callbacks-2`

**Comment by gucio321** [comment]
closing as a duplicate of #224
