### ISSUE TITLE
Add comments to enums/structs/funcs etc.

### ISSUE THREAD

**Issue by eliasdaler** [AllenDang/cimgui-go#27]
Apparently, cimgui added comment support not that long ago, see https://github.com/cimgui/cimgui/issues/212.
This is great, because we can add comments to struct getters, enum values and so on.

I'm adding this issue to track progress. For example, see this file as an example of what can be generated:
https://github.com/eliasdaler/cimgui-go/blob/enum_comments/cimgui_enums.go

Thoughts? :)

**Comment by AllenDang** [comment]
That will be great!

**Comment by gucio321** [comment]
well, despite I didn't tag this, that isseue is already fixed in #136
