### ISSUE TITLE
implot internal support?

### ISSUE THREAD

**Issue by SuperGod** [AllenDang/cimgui-go#28]
I want to draw candlestick.  In the implot [example](https://github.com/epezent/implot/blob/master/implot_demo.cpp#L2389), some internal functions must be used.

I tried to modify a little code. It seems to work normally, but I'm not sure whether there is a bug.

**Comment by runrc** [comment]
I too have a similar requirement. 

The implot example mentioned by @SuperGod makes references to internal functions defined in [implot_internal.h](https://github.com/epezent/implot/blob/master/implot_internal.h) for example `ImPlot::RoundTime`. These functions are defined in [cimplot.h](https://github.com/AllenDang/cimgui-go/blob/main/cimplot/cimplot.h) in cimgui-go but for some reason are not in the generated [cimplot_funcs.go](https://github.com/AllenDang/cimgui-go/blob/main/cimplot_funcs.go)

**Comment by hallum** [comment]
I ran into this issue a couple months back as well when I wanted to do some custom candlestick graphs following the same implot example.  I found the code below in the generator is what prevents the C functions from being wrapped for Go.  In my local copy I commented out this section and re-generated the code for cimplot (I did not re-run for cimgui) and was able to successfully get the candlestick demo running.  I did not submit a pull request as I do not know if this would expose problems with cimgui or if there is another reason for keeping the internal funcs hidden.  

https://github.com/AllenDang/cimgui-go/blob/main/cmd/codegen/gencpp.go#L69

`if len(f.FuncName) == 0 || strings.Contains(f.Location, "internal") { 
			shouldSkip = true
}`

**Comment by SuperGod** [comment]
> I ran into this issue a couple months back as well when I wanted to do some custom candlestick graphs following the same implot example. I found the code below in the generator is what prevents the C functions from being wrapped for Go. In my local copy I commented out this section and re-generated the code for cimplot (I did not re-run for cimgui) and was able to successfully get the candlestick demo running. I did not submit a pull request as I do not know if this would expose problems with cimgui or if there is another reason for keeping the internal funcs hidden.
> 
> https://github.com/AllenDang/cimgui-go/blob/main/cmd/codegen/gencpp.go#L69
> 
> `if len(f.FuncName) == 0 || strings.Contains(f.Location, "internal") { shouldSkip = true }`

I have modified some code locally. It is not enough to only modify this line. I can submit a pr after I have tested it.

**Comment by WinPooh32** [comment]
I made fork with enabled implot internal features.
https://github.com/WinPooh32/cimgui-go

There are not much [changes](https://github.com/AllenDang/cimgui-go/commit/f7b3ac39fe8a2d1686b0d5ffd46e15615ea8f1c7) to make it work.
Full list of skipped ImPlot functions:
https://gist.github.com/WinPooh32/e33e155a3df135fc96aac35fb45f03a7

Also successfully ported candlestick plot demo.  Some helper functions can be easily implemented using standard go library (binary search and time conversions).
Demo: https://github.com/WinPooh32/cimgui-candlestick-demo

@gucio321, but there is issue with code generation, these functions were generated with same names: 
https://github.com/WinPooh32/cimgui-go/blob/3477c3023e4a3a394efbec64389d6ef2595fe822/cimplot_funcs.go#L413-L431
```
func (self PlotItemGroup) ItemID(label_id string) ID {
	label_idArg, label_idFin := wrapString(label_id)
	defer func() {
		label_idFin()
	}()
	return ID(C.ImPlotItemGroup_GetItemID(self.handle(), label_idArg))
}

func (self PlotItemGroup) ItemID(id ID) PlotItem {
	return (PlotItem)(unsafe.Pointer(C.ImPlotItemGroup_GetItem_ID(self.handle(), C.ImGuiID(id))))
}
```

**Comment by gucio321** [comment]
@WinPooh32 looks great! Please open a pr. 
In case of these methods, in gengo_funcs there is a nap of functions that needs to be renamed somehow and another one for skipping then.
You need to handle duplicated functions there
