### ISSUE TITLE
An error occurred while running the demo, why？

### ISSUE THREAD

**Issue by farmer-simon** [AllenDang/cimgui-go#289]
# command-line-arguments
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running g++ failed: exit status 1
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.text+0x3d7a): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.text+0x3eed): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.text+0x700a): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.text+0xb9d1): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.xdata+0x804): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.xdata+0x87c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.xdata+0x8cc): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.xdata+0xa04): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.xdata+0xa38): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimgui.cpp.obj):cimgui.cpp:(.xdata+0xc0c): more undefined references to `__gxx_personality_seh0' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimmarkdown.cpp.obj):cimmarkdown.cp:(.text$_ZN5ImGui8MarkdownEPKcyRKNS_14MarkdownConfigE[_ZN5ImGui8MarkdownEPKcyRKNS_14MarkdownConfigE]+0x1246): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimmarkdown.cpp.obj):cimmarkdown.cp:(.xdata$_ZN5ImGui8MarkdownEPKcyRKNS_14MarkdownConfigE+0x2c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimmarkdown.cpp.obj):cimmarkdown.cp:(.xdata+0x50): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimplot.cpp.obj):cimplot.cpp:(.xdata+0x998): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimplot.cpp.obj):cimplot.cpp:(.xdata+0xa90): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimplot.cpp.obj):cimplot.cpp:(.xdata+0xadc): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(cimplot.cpp.obj):cimplot.cpp:(.xdata+0xb3c): more undefined references to `__gxx_personality_seh0' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0xeb1b): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0x297e6): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0x2a46a): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0x2b2e5): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0x31340): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0x3be37): more undefined references to `_Unwind_Resume' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.xdata+0x320): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.xdata+0x8c8): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.xdata+0x8ec): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.xdata+0x9bc): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.xdata+0x17e0): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui.cpp.obj):imgui.cpp:(.xdata+0x1814): more undefined references to `__gxx_personality_seh0' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text+0x89e3): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text+0x10771): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text+0x10786): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text+0x19804): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text+0x1bac2): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text+0x1c8d5): more undefined references to `_Unwind_Resume' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata+0x20): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata+0x30): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata+0x40): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata+0x50): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata+0x60): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata+0x70): more undefined references to `__gxx_personality_seh0' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text$_ZN17ExampleAppConsoleC1Ev[_ZN17ExampleAppConsoleC1Ev]+0x459): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata$_ZN17ExampleAppConsoleC1Ev+0xc): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text$_ZN17ExampleAppConsole16TextEditCallbackEP26ImGuiInputTextCallbackData[_ZN17ExampleAppConsole16TextEditCallbackEP26ImGuiInputTextCallbackData]+0x51b): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata$_ZN17ExampleAppConsole16TextEditCallbackEP26ImGuiInputTextCallbackData+0x18): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text$_ZN13ExampleAppLog4DrawEPKcPb[_ZN13ExampleAppLog4DrawEPKcPb]+0x543): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata$_ZN13ExampleAppLog4DrawEPKcPb+0x1c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.text$_ZN19ExampleAppDocumentsC1Ev[_ZN19ExampleAppDocumentsC1Ev]+0x4c4): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_demo.cpp.obj):imgui_demo.cpp:(.xdata$_ZN19ExampleAppDocumentsC1Ev+0x14): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.text+0xfcd2): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.text+0x13ccf): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.text+0x1a986): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.xdata+0x83c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.xdata+0x914): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.xdata+0x92c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.xdata+0xa98): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.xdata+0xb78): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_draw.cpp.obj):imgui_draw.cpp:(.xdata+0xc54): more undefined references to `__gxx_personality_seh0' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_tables.cpp.obj):imgui_tables.c:(.text+0xe40c): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_tables.cpp.obj):imgui_tables.c:(.text+0xec15): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_tables.cpp.obj):imgui_tables.c:(.text+0x105ee): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_tables.cpp.obj):imgui_tables.c:(.xdata+0x540): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_tables.cpp.obj):imgui_tables.c:(.xdata+0x58c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_tables.cpp.obj):imgui_tables.c:(.xdata+0x5d4): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_tables.cpp.obj):imgui_tables.c:(.xdata+0x6d8): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_widgets.cpp.obj):imgui_widgets.:(.text+0x14686): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_widgets.cpp.obj):imgui_widgets.:(.text+0x1a283): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_widgets.cpp.obj):imgui_widgets.:(.text+0x1a493): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_widgets.cpp.obj):imgui_widgets.:(.xdata+0x900): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_widgets.cpp.obj):imgui_widgets.:(.xdata+0xcdc): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_widgets.cpp.obj):imgui_widgets.:(.xdata+0xd14): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imnodes.cpp.obj):imnodes.cpp:(.xdata+0x148): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imnodes.cpp.obj):imnodes.cpp:(.xdata+0x174): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imnodes.cpp.obj):imnodes.cpp:(.xdata+0x23c): more undefined references to `__gxx_personality_seh0' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.text+0xac57): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.text+0x1cbac): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.text+0x2fa6a): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.text+0x2ffce): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.xdata+0x10): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.xdata+0x20): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.xdata+0x150): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.xdata+0x1b8): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.xdata+0x434): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot.cpp.obj):implot.cpp:(.xdata+0xaf8): more undefined references to `__gxx_personality_seh0' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.text+0x1201): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.text+0x4a00): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.text+0x59bc): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.text+0x5dee): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.text+0x68b6): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.text+0xb136): more undefined references to `_Unwind_Resume' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.xdata+0x2c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.xdata+0x3c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.xdata+0x4c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.xdata+0x5c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.xdata+0x6c): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(implot_demo.cpp.obj):implot_demo.cp:(.xdata+0x7c): more undefined references to `__gxx_personality_seh0' follow
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_impl_sdl2.cpp.obj):imgui_impl_sdl2.cpp:(.text+0x2bcf): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_impl_sdl2.cpp.obj):imgui_impl_sdl2.cpp:(.xdata+0xf4): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_impl_sdl2.cpp.obj):imgui_impl_sdl2.cpp:(.xdata+0x148): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_impl_opengl3.cpp.obj):imgui_impl_opengl3.cpp:(.text+0x562): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_impl_opengl3.cpp.obj):imgui_impl_opengl3.cpp:(.text+0x174e): undefined reference to `_Unwind_Resume'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_impl_opengl3.cpp.obj):imgui_impl_opengl3.cpp:(.xdata+0x40): undefined reference to `__gxx_personality_seh0'
C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240611070805-39b5aa2438db/lib/windows/x64\cimgui.a(imgui_impl_opengl3.cpp.obj):imgui_impl_opengl3.cpp:(.xdata+0xf8): undefined reference to `__gxx_personality_seh0'
collect2.exe: error: ld returned 1 exit status

**Comment by gucio321** [comment]
What os and arch? What code? Please do not work inside gomod path

**Comment by gucio321** [comment]
closing as no reply
