### ISSUE TITLE
dxguid & dxerr8 Prevent Cross-Compile on Linux Targeting Windows

### ISSUE THREAD

**Issue by xEricL** [AllenDang/cimgui-go#291]
I am cross compiling an app with Zig (v0.11.0) on Ubuntu 22.04 to be used on Windows. It appears the two libraries dxguid & dxerr8 cannot be found. Is there a way around this?

Here is the error:
```
/opt/hostedtoolcache/go/1.22.5/x64/pkg/tool/linux_amd64/link: running zig failed: exit status 1
error: unable to find Dynamic system library 'dxguid' using strategy 'paths_first'. searched paths:
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxguid.dll
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxguid.lib
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/libdxguid.a
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxguid.dll
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxguid.lib
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/libdxguid.a
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxguid.dll
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxguid.lib
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/libdxguid.a
error: unable to find Dynamic system library 'dxerr8' using strategy 'paths_first'. searched paths:
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxerr8.dll
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxerr8.lib
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/libdxerr8.a
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxerr8.dll
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxerr8.lib
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/libdxerr8.a
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxerr8.dll
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/dxerr8.lib
  /home/runner/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-2024071[105](https://github.com/alpine-client/pinnacle/actions/runs/10071331690/job/27841297791#step:12:106)5741-4b4d3ac1ee30/lib/windows/x64/libdxerr8.a
  ```
  
 Here is the [full log](https://productionresultssa14.blob.core.windows.net/actions-results/799e217e-0a81-42eb-bb54-d5a7777b23e9/workflow-job-run-66e6259c-52ff-5295-bc25-1d72233f8059/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-24T06%3A20%3A51Z&sig=VTtsW7v3nuVzffEz26j7AEcuYhlyA1DTvgRldRzTU6k%3D&ske=2024-07-24T18%3A09%3A52Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-24T06%3A09%3A52Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-07-24T06%3A10%3A46Z&sv=2024-05-04) from the GitHub actions workflow where I've been trying to do this. 
 
 Here is the [workflow file](https://github.com/alpine-client/pinnacle/blob/master/.github/workflows/go-build.yml) if that helps at all.
 
 
 **Notes:** There is a chance this is caused by [an issue fixed in Zig 0.12.0](https://github.com/ziglang/zig/pull/17218). However, when I try using Zig v0.12.0+ to compile my app, Zig can't see that `cimgui.a`, `libglfw3.a`, and `libSDL2.a` are located in [/lib/windows/x64/](https://github.com/AllenDang/cimgui-go/tree/main/lib/windows/x64).
(Maybe because of [this issue](https://github.com/ziglang/zig/issues/20689)?)
My C knowledge is very limited, so I can't say for certain. I was hoping you guys could look into this and let me know if this is an issue with Zig or cimgui-go.

Any help would be greatly appreciated.

**Comment by AllenDang** [comment]
I know nothing about zig so I might not be able to help here.

**Comment by gucio321** [comment]
@xEricL its also my first time when I hear about zig.

I think you need to care about some type of `PATH` or `INCLUDE_PATH` in zig, however it works.
generally, in cimgui.go file is a list of C/C++/Linker flags that your compiler needs to read and use. You can try to copy-paste them in your command line and check - it may work...

**Comment by xEricL** [comment]
The weird thing is that my cross-compiling worked when my app was using Giu v0.7 but when I upgraded to Giu v0.8 + cimgui it broke, so I was thinking it was because of a difference in cimgui (which is why I created the issue in this repo). 

I will continue researching and keep you guys updated here. A lot of developers use Zig for cross compiling CGO, so I'm sure I won't be the last to run into this problem.

**Comment by xEricL** [comment]
@gucio321 Is there a reason `cimgui.a` in `/lib/windows/x64/` isn't following the naming convention for libraries? Like how glfw3 is called `libglfw3.a` and SDL2 is called `libSDL2.a`? I figured out how to get Zig to look in `/lib` folder but it keeps looking for `libcimgui.a` instead of `cimgui.a`.

```
| error: unable to find dynamic system library 'cimgui' using strategy 'paths_first'. searched paths:
|   /root/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/cimgui.dll
|   /root/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/cimgui.lib
|   /root/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64/libcimgui.a
```

This is my build command
```bash
env GOARCH=amd64 GOOS=windows \
CC="zig cc -target x86_64-windows-gnu -Wl,--subsystem,windows -Wl,-s" \
CXX="zig c++ -target x86_64-windows-gnu -Wl,--subsystem,windows -Wl,-s" \
CGO_CFLAGS="-I/root/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64" \
CGO_LDFLAGS="-L/root/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20240711055741-4b4d3ac1ee30/lib/windows/x64 -lcimgui -lglfw3 -lSDL2" \
go build -trimpath -p 4 -ldflags="-H=windowsgui" -o bin/pinnacle-windows-amd64.exe .
```

**Comment by gucio321** [comment]
But it isn't /lib its $PKGDIR/lib

These paths are set in cimgui.go file

**Comment by gucio321** [comment]
Btw I undersrand meaning convention note and yeah, if this is a standard we should change to libcimgui

**Comment by gucio321** [comment]
Are you sure you need to specify these LDFLAGS in your zig command?

**Comment by gucio321** [comment]
Are you sure you need to specify these LDFLAGS in your zig command?

**Comment by xEricL** [comment]
> Are you sure you need to specify these LDFLAGS in your zig command?

I'm not 100% sure. Honestly I've just been trying everything to get it to work. The biggest issue is that `dxguid` and `dxerr8` can't be found (like in the original post). Do you know where it should be finding that library?

**Comment by xEricL** [comment]
@gucio321 I just need to be able to cross-compile for Windows on Linux. Have you guys been able to do that after giu migrated to cimgui-go in v0.8?

**Comment by gucio321** [comment]
dx* sounds like direcx library. What requires that ? I think cimgui-go uses glfw with opengl

**Comment by gucio321** [comment]
in case of cross-compilation for windows: I used to do that with mingw:
```sh
CC="x86_64-w64-mingw32-gcc" CXX="x86_64-w64-mingw32-g++" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" go build -o widgets.exe .
```

This method iirc is described somewhere in giu docs.

**Comment by gucio321** [comment]
here is a workflow using that method: https://github.com/gucio321/tic-tac-go/blob/master/.github/workflows/build.yml

**Comment by xEricL** [comment]
> dx* sounds like direcx library. What requires that ? I think cimgui-go uses glfw with opengl

The only place it is mentioned is here.
https://github.com/AllenDang/cimgui-go/blob/4b4d3ac1ee3063ee5ecdc89044b664b6d53dc5e1/sdl_backend.go#L6

**Comment by gucio321** [comment]
@xEricL can we close this? I think that the original issue was fixed (mingw compilation works)?
