### ISSUE TITLE
How to constrain a Tooltip to a window?

### ISSUE THREAD

**Issue by Omustardo** [AllenDang/cimgui-go#295]
I noticed some odd behavior when the tooltip goes over the edge of the window. On Debian 12 (I can collect more info about my system if needed, but it's basically vanilla Debian), the tooltip creates a new window named "No Title Yet". This new window takes focus away from the original window, and feels a bit bit laggy.

Demo: https://github.com/user-attachments/assets/51065f86-4d96-4625-bfa7-6b5dcc99a8ca
Code: https://gist.github.com/Omustardo/e1bb32296d0b51b88bc12133e6bb8667

A slightly more minimal example:
```
	vp := imgui.MainViewport()
	imgui.SetNextWindowPosV(vp.Pos(), imgui.CondOnce, imgui.NewVec2(0, 0))
	imgui.SetNextWindowSize(vp.Size())
	imgui.BeginV("Window1", nil, 0)
	{
		imgui.Text("TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST")
		if imgui.BeginItemTooltip() {
			imgui.Text("TOOLTIP")
			imgui.EndTooltip()
		}
	}
	imgui.End()
```
To reproduce, mouseover the "TEST TEST" content all the way on the right of it, so that the tooltip goes outside of the native OS window.

---

Is there a reliable way constrain a tooltip to the window that its creation was triggered from?
I can do it by calculating the size of the tooltip and using `SetNextWindowPos`. This is fine for text tooltips, but if I had more widgets in the tooltip it might be a pain. https://gist.github.com/Omustardo/bbf784a6865809d54fed493e42a0e964

I expect this is an issue in https://github.com/ocornut/imgui/ since it deals with just the C bindings. I reported it in this repo rather than that one because I haven't tested it in C.

**Comment by gucio321** [comment]
I have to say the famous clause: "Its not a bug, its a feature".
To disable this feature, you need to disable one of the Docking features
enabled here in glfw_backend.cpp:
```cpp
  io->ConfigFlags |= ImGuiConfigFlags_DockingEnable;   // Enable Docking
  io->ConfigFlags |= ImGuiConfigFlags_ViewportsEnable; // Enable Multi-Viewport
```

**Comment by Omustardo** [comment]
Thanks! I tested with:

1. `imgui.CurrentIO().SetConfigFlags(imgui.ConfigFlagsDockingEnable | imgui.ConfigFlagsViewportsEnable)` -> This resulted in the tooltip being in a new window.
2. `imgui.CurrentIO().SetConfigFlags(imgui.ConfigFlagsDockingEnable)` : The tooltip stayed in the main window.
3. `imgui.CurrentIO().SetConfigFlags(imgui.ConfigFlagsViewportsEnable)` : The tooltip escaped to a new window.

So I think it's only the multi-viewport flag that's doing it.

Here's a demo for future readers that avoids messing with existing imgui flag defaults: https://gist.github.com/Omustardo/960ddadd4124a698d76a6ba55d5dccb8

The core of it is:
```
imgui.CurrentIO().SetConfigFlags(imgui.CurrentIO().ConfigFlags() & ^imgui.ConfigFlagsViewportsEnable)
```
and it has to be called anytime after `backend.CreateWindow()`

**Comment by gucio321** [comment]
because for some reason it is the default in glfw backend.
I'm not sure what should we do with that tbh... Maybe this shouldn't be default (?)

**Comment by Omustardo** [comment]
Is this a default from Dear Imgui, or is it part of this repo? If it's part of Dear Imgui then I'd leave it the same for consistency. If it's custom to this repo then making it not the default could be reasonable. I'm not sure which option is better:
* People expecting multiple viewports to work out of the box, and having to figure out that they need `ConfigFlagsViewportsEnable`
* People experiencing this tooltip issue (and maybe other unexpected behavior), and having to figure out that they need to disable `ConfigFlagsViewportsEnable`
