### ISSUE TITLE
Way we choose backends

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#298]
At the moment, we have "opt-out" backend policy - to exclude one of C backends we need to set `exclude_cimgui_XXX` go tag.
Since #296, when we have Ebiten backend, I suggest switching to "opt-in" backend policy.
- ebiten backend is already opt-in as its in a separated go package
- C backends cannot be moved away from the main package, so I suggest adding tags to enable them (`include_cimgui_XXX)

It will be nice thing to do, because various backends conflicts with each other.

**Comment by AllenDang** [comment]
Agree, sounds good.
