### ISSUE TITLE
build giu failed with latest cimgui-go

### ISSUE THREAD

**Issue by lzytaro** [AllenDang/cimgui-go#302]
Please do not modify the library path; otherwise, the giu compilation exception will occur. If you must modify the giu code, modify it simultaneously。 @gucio321 

..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Context.go:45:30: undefined: imgui.GLFWWindowFlags
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Context.go:67:42: undefined: imgui.GLFWWindowFlags
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Context.go:128:49: undefined: imgui.GLFWWindowFlags
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Flags.go:54:24: undefined: imgui.GLFWWindowFlags
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\MasterWindow.go:31:64: undefined: imgui.GLFWWindowFlags
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\MasterWindow.go:57:30: undefined: imgui.GLFWWindowFlags
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Keycode.go:97:32: undefined: imgui.GLFWKeyKp0
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Keycode.go:98:32: undefined: imgui.GLFWKeyKp1
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Keycode.go:99:32: undefined: imgui.GLFWKeyKp2
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Keycode.go:100:32: undefined: imgui.GLFWKeyKp3
..\..\pkg\mod\github.com\!allen!dang\giu@v0.8.1\Keycode.go:100:32: too many errors

**Comment by gucio321** [comment]
Giu is a separated go module. It has its own go.mod file with specified cimgui-go version which is supposed to be used.

**Comment by lzytaro** [comment]
> Just btw, what the hell are you doing that you experiences such a crash 😁
> 
> I didn't think it's even possible 😲 Matce your project also has cimgui-go dependency?
> 
> If not maybe we should report an issue in go repo as imo it isn't supposed

As you said, my project uses the latest cimgui-go. After the directory adjustment, some of the latest definitions that giu relies on cannot be found, resulting in the inability to compile.

**Comment by gucio321** [comment]
> As you said, my project uses the latest cimgui-go. After the directory adjustment, some of the latest definitions that giu relies on cannot be found, resulting in the inability to compile.

Generally in projects using GIU it is recommended to use cimgui-go version compatible with giu cimgui-go version.

Anyway I have no idea why `go` decided to take newer version of cimgui-go (prioritize version from your go.mod than from giu's go.mod)
Generally cimgui-go is on `v0.0.0` for go so it is absolutly not stable yet...

Btw I did a quick test and managed to reproduce your issue. I recommend switching for supported vcimgui-go version for now. I'll update giu later.

**Comment by gucio321** [comment]
https://github.com/golang/go/issues/69437 they will not change it.
