### ISSUE TITLE
float* arg wrapper error

### ISSUE THREAD

**Issue by SuperGod** [AllenDang/cimgui-go#31]
The "float *" of some method's arg represents a float array, but the current code is represented as the address of a float number. This wrapper is incorrect. I have seen the following functions, but there may be some I don't see:

```
// rows is array length and row_ratios is row array,cols is array length and col_ratios is column array
CIMGUI_API bool ImPlot_BeginSubplots(const char *title_id, int rows, int cols, const ImVec2 size,
                                     ImPlotSubplotFlags flags, float *row_ratios, float *col_ratios);

```

The current code is:
[wrapFloat](https://github.com/AllenDang/cimgui-go/blob/main/type_wrapper.go#L45)
```
func wrapFloat(goValue *float32) (wrapped *C.float, finisher func()) {
	if goValue != nil {
		cValue := C.float(*goValue)
		wrapped = &cValue
		finisher = func() {
			*goValue = float32(cValue)
		}
	} else {
		finisher = func() {}
	}
	return
}
```

The following simple modifications will work, but it may not be a good idea to directly access the go value addr from c code

```
func wrapFloat(goValue *float32) (wrapped *C.float, finisher func()) {
	if goValue != nil {
		wrapped = (*C.float)(unsafe.Pointer(goValue))
		finisher = func() {}
	} else {
		finisher = func() {}
	}
	return
}
```

**Comment by gucio321** [comment]
So, I think, that we should add another map with _name of arguments that are of type `float*` and are supposed to be `[]float32` in go rather than `*float32`_

**Comment by gucio321** [comment]
@SuperGod #179 I've added SliceToPtr method that could be used in this case

**Comment by gucio321** [comment]
And we can't do anything else here, so closing it.
