### ISSUE TITLE
Using OpenGL calls with SDL backend

### ISSUE THREAD

**Issue by Bradbev** [AllenDang/cimgui-go#325]
I am currently using the SDL/GL backend on MacOS (M2 machine).  My usecase is that I want to build a toy shader app to learn more about OpenGL and sit Imgui on top on the scene for variable control.  From what I can see, it's not possible to issue gl calls from your own code very easily.  I had expected that in my loop function I would be able to make OpenGL function calls, but I think the order of operations in https://github.com/AllenDang/cimgui-go/blob/main/backend/sdlbackend/sdl_backend.cpp#L184 means that the GL buffers will be cleared after the loop.
Is my usecase outside the intended scenarios?

I think moving [these lines](https://github.com/AllenDang/cimgui-go/blob/main/backend/sdlbackend/sdl_backend.cpp#L190-L192) above the call to loop would allow my usecase to work - ie, from the loop() callback, you would be able to draw both ImGUI graphics and make OpenGL calls.

**Comment by gucio321** [comment]
@Bradbev If this change will not break anything I think you can open a PR.

**Comment by gucio321** [comment]
@anasrar sure, could you open a pr

**Comment by anasrar** [comment]
Test on Linux, SDL also not triggered any callback. Should I create new issue for this ?

**Comment by anasrar** [comment]
@gucio321 commenting this line before return works fine.

https://github.com/AllenDang/cimgui-go/blob/1a15ba4f9967007a718c40ef7a9fedd6807eeed5/backend/glfwbackend/glfw_backend.cpp#L118-L119

**Comment by gucio321** [comment]
Maybe incompatible versions? We do not use go-gl version of the bindings

**Comment by anasrar** [comment]
@gucio321 The problem is GLFW context set to null after create window, fixed.
