### ISSUE TITLE
Add project to Awesome Go

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#329]
[Awesome GO](https://github.com/avelino/awesome-go) is a project that lists awesome go projects :smile: cimgui-go is awesome so it should be there ofc.
The following things should be checked first:
- [x] have an open source license, [see list of allowed licenses](https://opensource.org/licenses/alphabetical); We have MIT so it is open source enough.
- [x] function as documented and expected;
- [X] be generally useful to the wider community of Go programmers; Of course!
- [X] be actively maintained with: Generally yes.
   - regular, recent commits;
   - or, for finished projects, issues and pull requests are responded to generally within 2 weeks;
- [X] be stable or progressing toward stable; everything works. there are some feautres that we're working on but generally the project is stable.
- [X] be thoroughly documented (README, pkg.go.dev doc comments, etc.) in the English language, so everyone is able to understand the project's intention and how it works. All public functions and types should have a Go-style documentation header; There is a readme, there are also sub-readmies for some more important packages; go function/type comments are also auto-generated so as long as our 3rd party projects generates correctly, comments are here. If user needs additional documentation, it is recommended to refer to our upstream (Dear ImGui)
- [X] if the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data-related packages. (Note: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark result); Does not apply. cimgui-go is a wrapper of C code so testing it isn't really possible.
- [X] have at least one official version-numbered release that allows go.mod files to list the file by version number of the form vX.X.X. v1.0.0 was relased on september 24 2024

**Comment by gucio321** [comment]
@AllenDang looks like we meet every requirement from the list https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards

Can I proceed to awesome-go?

**Comment by AllenDang** [comment]
@gucio321 Let's do it

**Comment by phanirithvij** [comment]
Can `gofmt -s` be run on the generated bindings?

**Comment by gucio321** [comment]
Dedicated issue for `gofmt` was opened.
Now we're in awesome-go :tada:
