### ISSUE TITLE
Add a sample of how to use immarkdown

### ISSUE THREAD

**Issue by ptxmac** [AllenDang/cimgui-go#331]
I've been trying to use `immarkdown`, but something seems missing.
the `Markdown` method needs a `MarkdownConfig` object, but there's no way to create one correctly and the program just fails with a nil access

If it's supposed to work as is, please add a small sample demonstrating how

**Comment by gucio321** [comment]
Unfortunately as I said in release notes immarkdown is not fully functional as it misses callbacks impl for now.
Turns out that imgui_markdown doesn't provide NewMarkdownConfig function.
Maybe `cmd/codegen/gengo_typedefs.go` should also generate `CreateEmptyXXX` for all types?
```go
func CreateEmptyXXX() XXX {
   return XXX{
      CData: new(C.XXX),
   }
}
```

@AllenDang what do you think about it?

Anyway, this will not work even if we add such a functions because then it'll panic for some reason. I suppose it needs to have FormatCallback set.

**Comment by AllenDang** [comment]
@gucio321 I don't have experience about immarkdown, so I cannot give an useful comment here...

**Comment by gucio321** [comment]
well, I think that overall, such a function would be useful.

**Comment by gucio321** [comment]
Ok, I found what's going on here.
Even with `NewEmptyMarkdownConfig` `imgui_markdown` code here
https://github.com/AllenDang/cimgui-go/blob/b4c397e4914299c470c2a409b1c627188df40480/cwrappers/imgui_markdown/imgui_markdown.h#L513
calls formatCallback which we have no way to set atm.
Unfortunately that means imguimarkdown is useless as long as #224 isn't fixed.

**Comment by gucio321** [comment]
Progress mad on #224 . 
Now htis is frozen by #372

**Comment by gucio321** [comment]
it works now:

in _vars_ section
```go
var (
        markdownConfig *immarkdown.MarkdownConfig
        markdownText   string = `
Hello [world](https://github.com/AllenDang/cimgui-go) from md
`
)
```

in initialization:

```go
        markdownConfig = immarkdown.NewMarkdownConfigEmpty()
        cb := func(info immarkdown.MarkdownFormatInfo, start bool) {
        }

        markdownConfig.SetFormatCallback((*immarkdown.MarkdownFormalCallback)(&cb))
```

in loop:
```go
        basePos := imgui.MainViewport().Pos()
        imgui.SetNextWindowPosV(imgui.NewVec2(basePos.X+400, basePos.Y+460), imgui.CondOnce, imgui.NewVec2(0, 0))
        imgui.SetNextWindowSizeV(imgui.NewVec2(400, 250), imgui.CondOnce)
        imgui.Begin("Markdown demo")
        immarkdown.Markdown(markdownText, uint64(len(markdownText)), *markdownConfig)
        imgui.End()
```

there are pointers in some strange places but we can't do anything about it right now...
