### ISSUE TITLE
Example: image not working

### ISSUE THREAD

**Issue by asmaloney** [AllenDang/cimgui-go#35]
- macOS 12.6.1
- Radeon Pro 580X 8 GB

Using the code (and the _test.jpeg_ file) in the example directory, I get this:

<img width="1043" alt="Screen Shot 2022-11-23 at 15 17 38 PM" src="https://user-images.githubusercontent.com/391371/203639576-4b5baf66-6501-436c-a073-763dd26f87b4.png">

Tried with a PNG - same result.

The rest works though - cool!

**Comment by hexvalid** [comment]
Can you try load texture on **afterCreateContext** function?
Like this:

```
       cimgui.SetAfterCreateContextHook(func() {
			texture = cimgui.CreateTextureRgba(...,...,...)
	})
	...
	window.Run(uiLoop)
```

**Comment by asmaloney** [comment]
It does indeed! Thanks @hexvalid.

(PR incoming...)
