### ISSUE TITLE
Style Getters require pointer, but setters don't

### ISSUE THREAD

**Issue by Wieku** [AllenDang/cimgui-go#351]
I've just noticed that `imgui.CurrentContext().Style()` returns a struct, not pointer, but style getters require a pointer, but setters don't:

https://github.com/AllenDang/cimgui-go/blob/c39c7e5756aed4af83b92429ffbc7e4390227f1a/imgui/cimgui_funcs.go#L29328-L29341

It works fine if I do this:
```go
cStyle := imgui.CurrentContext().Style()
bSize := (&cStyle).WindowBorderSize()
```

But given that Style struct already holds a pointer I don't think there's a need for getter receivers to require a pointer as well. Unless I'm missing something :p

**Comment by gucio321** [comment]
@Wieku I think you should use `imgui.CurrentStyle` instead as it returns pointr

**Comment by gucio321** [comment]
let me close this for now. LMK if you still need help here.
