### ISSUE TITLE
[Question] Strings : Are they copied when passing them to the ImGUI C code?

### ISSUE THREAD

**Issue by system64MC** [AllenDang/cimgui-go#399]
Hello! I have a question about strings. I saw that you convert them to C Strings before passing them to Dear ImGUI. I've also heard that the data is copied during C string conversion.

Is it also the case for Cimgui-Go? Wouldn't it hurt performances too much? Knowing the fact strings are involved a lot in Dear ImGUI. 
Great work by the way! I used your Giu framework to build an app that people still use!

Thanks for your answer.

**Comment by AllenDang** [comment]
According to cgo's document https://go.dev/wiki/cgo#go-strings-and-c-strings the string will be copied. For performance impact, I didn't experience the performance impact so far, so I think it performs well enough.
