### ISSUE TITLE
gitattributes: tell github to hide diffs of auto-generated files

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#44]
Hi!
As far as I remember, there is a special `.gitattributes` file (or something like that), when you can tell GitHub not to display certain files since they're aut-generated. It could be useful while reviewing Pull Requests

**Comment by gucio321** [comment]
here is a reference doc: https://git-scm.com/docs/gitattributes

**Comment by gucio321** [comment]
I can take a look a bit later

**Comment by eliasdaler** [comment]
Which files would you like to see hidden?

**Comment by gucio321** [comment]
I think, that everything auto-generated;

**Comment by eliasdaler** [comment]
By "auto-generated" stuff I assume you're talking about files like "cimgui_funcs.go"? Then we **don't** want them to be excluded from diffs because they're results of generation. We **should** see if the results of generation change because that's how we'll see if something breaks or not.

**Comment by gucio321** [comment]
> By "auto-generated" stuff I assume you're talking about files like "cimgui_funcs.go"?

yes, exactly

>  We should see if the results of generation change because that's how we'll see if something breaks or not.

by "excluding from diffs" I meant, that GitHub, instead of showing the full diff, should say "hidden Aut-generated file. Show More" (or similar). We can see the diff after clicking on "Show More" but it is hidden by default.

**Comment by gucio321** [comment]
https://git-scm.com/docs/gitattributes#_generating_diff_text
hmm, I wanted to use these attributes, but it seems that they cannot be used to do the trick.

**Comment by eliasdaler** [comment]
I want to see the full diff. It’s kinda the main thing we should care about in PRs - is cgo/go generated code correct, did API chane unexpectedly, etc.

**Comment by gucio321** [comment]
okey, so closing this

**Comment by gucio321** [comment]
@eliasdaler sorry for re-opening that, but accidently I found it:
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

and github will show it like that:

![image](https://user-images.githubusercontent.com/73652197/207139564-a344bd9f-a351-4cf8-8041-040298b59c2f.png)

**Comment by eliasdaler** [comment]
And which generated files would we *not want* to see? I want to see the generated file output. It's not "noise" that should be hidden.

**Comment by gucio321** [comment]
personally, I'd like to see _that_ something in auto-generated files has been changed, but I'd like to focus on the code that *caused their change* first.

**Comment by eliasdaler** [comment]
If the diff is large, it will be hidden anyway
If it's small, then I'd rather see a 10 line diff than have to click "show me" manually each time.

**Comment by gucio321** [comment]
well, I think that GitHub does it anyway :smile:
