### ISSUE TITLE
idea: use generics in type_wrapper.go

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#55]
after looking at code I got an idea, to use `go 1.19`'s generic to replace `wrap*` with one large generic method

**Comment by eliasdaler** [comment]
If generics make the code easier - sure
Otherwise, it might bring more troubles (switch-case/magical casts to any, etc.)

Not sure about which `CTYPE` you're talking about.

**Comment by gucio321** [comment]
> If generics make the code easier - sure
Otherwise, it might bring more troubles (switch-case/magical casts to any, etc.)

ofc it will simplify the code ;-)

> Not sure about which CTYPE you're talking about.

sorry, forgot to post the full code :smile:
it seems to work now, gonna fill a PR in a moment
