### ISSUE TITLE
PlotLines have wrong signature

### ISSUE THREAD

**Issue by ptxmac** [AllenDang/cimgui-go#6]
`PlotLines_FloatPtr` takes a float pointer instead of a slice. 
This would be fine if the pointer was forwarded to imgui, but instead it's dereferenced which means `PlotLines` only gets a single value

**Comment by ptxmac** [comment]
I re-ran the generator locally and got a new signature, so perhaps the main branch is just outdated?

**Comment by AllenDang** [comment]
This should be fixed, I've changed all const xx* to slice, maybe missed some file during check in.

**Comment by ptxmac** [comment]
> This should be fixed, I've changed all const xx* to slice, maybe missed some file during check in.

running the generator fixed it for me, so I think you just forgot to update the generated files

**Comment by AllenDang** [comment]
Ok, I regenerated all the bindings, it should be fixed.
