### ISSUE TITLE
Add a CI check that will run gencode_* and compare the output

### ISSUE THREAD

**Issue by eliasdaler** [AllenDang/cimgui-go#60]
People can potentially submit a PR without running gencode - we need to prevent this.
@gucio321, would be nice to do, since you're experienced in Github Actions :)

**Comment by gucio321** [comment]
> People can potentially submit a PR without running gencode - we need to prevent this.
@gucio321, would be nice to do, since you're experienced in Github Actions :)

I tought about it, but ater updating, what the CI should do?
push the updated code to owner's branch? Than, someone can find it noisy
or maybe just crash preventing PR from being merged, if diff != ""?

**Comment by eliasdaler** [comment]
It should just fail and ideally print diff in CI output, yeah.

**Comment by gucio321** [comment]
> It should just fail and ideally print diff in CI output, yeah.

ok, so the steps should be:
- install everything
- generate code
- run the following script:
```sh
diff=`git diff` # to show the diff in output.
if [ $diff != "" ]; then
   echo "There is git diff after generating code. Run \`just gencode_cimgui/gencode_cimplot\` and commit changes to make this job complete"
   echo "The diff is:"
    echo $diff
    exit 1
fi
```

**Comment by gucio321** [comment]
@eliasdaler and whats your opinion on GitHub action with only the `workflow_dispatch` trigger called "generate_code.yaml" that use can run if he want to update project, but doesn't want to play with just on his machine?

**Comment by eliasdaler** [comment]
This user can then ask us to run generation and we'll push commits to their PR. Adding "workflow_dispatch" trigger kinda sounds like a CI bloat.

**Comment by gucio321** [comment]
ok, so let me write this action

**Comment by gucio321** [comment]
ok @eliasdaler it is done; see #62
