### ISSUE TITLE
array args: automatically determine len of array

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#69]
Hi there!
There are some functions, e.g.
```h
CIMGUI_API bool igCombo_Str_arr(const char* label,int* current_item,const char* const items[],int items_count,int popup_max_height_in_items);
```
or in go
```go
func Combo_Str_arrV(label string, current_item *int32, items []string, items_count int32, popup_max_height_in_items int32) bool { ... }
```

These functions takes an array of strings as well as its length (if I understand the code correctly :smile:)
However, in go we can handle array's length with `len(...)` built-in function that isn't possible in C iirc.

Is there any way in cimgui JSON defs to recognize such a function like it ws for #11 ?

CC @sonoro1234

**Comment by AllenDang** [comment]
It's un-reliable to make this fully automatic, the rule might be defined like "a param has '_count' suffix with type int32 and follow a param with array", it might work, just not reliable. Same as to determine which one is a pointer aims to be returned.
I suggest not to spend too many effort in these areas.
cimgu-go is a one-to-one wrapper, don't do magic here.

**Comment by sonoro1234** [comment]
> Is there any way in cimgui JSON defs to recognize such a function like it ws for #11 ?

It is not comparable: nonUDT is related to a change made from C++ to C while the array length argument is present in both C++ and C.
Taking profit of array's length from go, Lua or whatever can be done in another wrapping level (not automatic magic)

**Comment by sonoro1234** [comment]
> "a param has '_count' suffix with type int32 and follow a param with array", it might work, just not reliable.

But could be reliable if @ocornut decides that this pattern is always used!!! (And it does not collide with other uses)

**Comment by eliasdaler** [comment]
I wouldn't want to use these functions because it's better for Go functions signatures to be as close to C++ API as possible. Makes it much easier to port Dear ImGui code from C++ to Go.

**Comment by ocornut** [comment]
I am happy to decide on a suitable pattern if useful for bindings generators, if you can be explicit with the functions that needs it.

**Comment by gucio321** [comment]
well, basing on above discussion I need to agree that it'd be better to leave it as-is. Closing.
