### ISSUE TITLE
ImGuiInputTextCallbackData.GetBuf is missing

### ISSUE THREAD

**Issue by ptxmac** [AllenDang/cimgui-go#7]
The c wrapper exists: `extern char* ImGuiInputTextCallbackData_GetBuf(ImGuiInputTextCallbackData *self);`

But there's no go counterpart

**Comment by AllenDang** [comment]
This is a little bit tricky, frankly I've never used `GetBuf` in real world...
Anyway, I will check the mapping function which handles the return value and get it be generated just to keep the binding as complete as possible.

**Comment by ptxmac** [comment]
For reference, I use it to do tab-completion / history in a Text input callback

**Comment by AllenDang** [comment]
@ptxmac It's done, it should be generated now.

**Comment by ptxmac** [comment]
Awesome! I'll have a look later 😄
