### ISSUE TITLE
Plot_GetPlotMousePos got panic

### ISSUE THREAD

**Issue by lzytaro** [AllenDang/cimgui-go#8]
add Plot_GetPlotMousePosV or Plot_GetPlotMousePos got panic info:

Exception 0xc0000005 0x1 0x0 0x7ff6347ef0a8
PC=0x7ff6347ef0a8
signal arrived during external code execution

runtime.cgocall(0x7ff6347be090, 0xc00011dc28)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc00011dc00 sp=0xc00011dbc8 pc=0x7ff6346e3f8a
github.com/AllenDang/cimgui-go._Cfunc_Plot_GetPlotMousePosV(0x0, 0x0, 0x0)
        _cgo_gotypes.go:46246 +0x52 fp=0xc00011dc28 sp=0xc00011dc00 pc=0x7ff634796532
github.com/AllenDang/cimgui-go.Plot_GetPlotMousePosV(...)
        E:/go_project/src/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20220916091242-73329c8fc841/cimplot_funcs.go:13
main.showImPlotDemo()
        E:/go_project/src/giu_widgets/main.go:93 +0x125 fp=0xc00011dc68 sp=0xc00011dc28 pc=0x7ff63479bea5
main.loop()
        E:/go_project/src/giu_widgets/main.go:107 +0x25 fp=0xc00011dc78 sp=0xc00011dc68 pc=0x7ff63479bf85
github.com/AllenDang/cimgui-go.glfwWindowLoopCallback(...)
        E:/go_project/src/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20220916091242-73329c8fc841/backend.go:90
_cgoexp_c837ec952769_glfwWindowLoopCallback(0x2e15824c220?)
        _cgo_gotypes.go:53313 +0x23 fp=0xc00011dc88 sp=0xc00011dc78 pc=0x7ff63479a8c3
runtime.cgocallbackg1(0x7ff63479a8a0, 0xc00011de48?, 0x0)
        C:/Program Files/Go/src/runtime/cgocall.go:314 +0x2ca fp=0xc00011dd58 sp=0xc00011dc88 pc=0x7ff6346e452a
runtime.cgocallbackg(0xc000050000?, 0x300000002?, 0xc000050000?)
        C:/Program Files/Go/src/runtime/cgocall.go:233 +0x106 fp=0xc00011ddf0 sp=0xc00011dd58 pc=0x7ff6346e4166
runtime.cgocallbackg(0x7ff63479a8a0, 0xf3625ff61f, 0x0)
        <autogenerated>:1 +0x36 fp=0xc00011de18 sp=0xc00011ddf0 pc=0x7ff63473ffd6
runtime.cgocallback(0x7ff6346e3feb, 0x7ff63479c430, 0xc00011dea8)
        C:/Program Files/Go/src/runtime/asm_amd64.s:971 +0xd7 fp=0xc00011de40 sp=0xc00011de18 pc=0x7ff63473ddf7
runtime.systemstack_switch()
        C:/Program Files/Go/src/runtime/asm_amd64.s:436 fp=0xc00011de48 sp=0xc00011de40 pc=0x7ff63473bce0
runtime.cgocall(0x7ff63479c430, 0xc00011dea8)
        C:/Program Files/Go/src/runtime/cgocall.go:167 +0xab fp=0xc00011de80 sp=0xc00011de48 pc=0x7ff6346e3feb
github.com/AllenDang/cimgui-go._Cfunc_igRunLoop(0x2e1581f9da0, 0x7ff63479c190, 0x7ff63479c1d0, 0x7ff63479c210, 0x7ff63479c290)
        _cgo_gotypes.go:53270 +0x52 fp=0xc00011dea8 sp=0xc00011de80 pc=0x7ff634797532
github.com/AllenDang/cimgui-go.GLFWwindow.Run.func1(0xc00000e1b0?)
        E:/go_project/src/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20220916091242-73329c8fc841/backend.go:72 +0x9b fp=0xc00011df08 sp=0xc00011dea8 pc=0x7ff6347978fb
github.com/AllenDang/cimgui-go.GLFWwindow.Run(0xc000068040?, 0xc000012300?)
        E:/go_project/src/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20220916091242-73329c8fc841/backend.go:72 +0x37 fp=0xc00011df20 sp=0xc00011df08 pc=0x7ff634797837
main.main()
        E:/go_project/src/giu_widgets/main.go:131 +0x178 fp=0xc00011df80 sp=0xc00011df20 pc=0x7ff63479c158
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:250 +0x1fe fp=0xc00011dfe0 sp=0xc00011df80 pc=0x7ff6347174de
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00011dfe8 sp=0xc00011dfe0 pc=0x7ff63473e061
rax     0xf3625ff460
rbx     0x0
rcx     0x0
rdi     0xc00011dc28
rsi     0x7ff634c24160
rbp     0xc00011dbf0
rsp     0xf3625ff440
r8      0x0
r9      0x0
r10     0x0
r11     0x1
r12     0x7ff634b1e8b0
r13     0x10
r14     0xc000050000
r15     0x2e17d73ffff
rip     0x7ff6347ef0a8
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

source code:

`var p cimgui.ImPlotPoint
var x,y cimgui.ImAxis

func showImPlotDemo() {
	basePos := cimgui.GetMainViewport().GetPos()
	cimgui.SetNextWindowPosV(cimgui.NewImVec2(basePos.X+400, basePos.Y+60), cimgui.ImGuiCond_Once, cimgui.NewImVec2(0, 0))
	cimgui.SetNextWindowSizeV(cimgui.NewImVec2(500, 300), cimgui.ImGuiCond_Once)
	cimgui.Begin("Plot window")
	if cimgui.Plot_BeginPlotV("Plot", cimgui.NewImVec2(-1, -1), 0) {
		cimgui.Plot_PlotLine_S64PtrInt("Line", barValues, int32(len(barValues)))

		cimgui.Plot_GetPlotMousePosV(p, x, y)
		//cimgui.Plot_GetPlotMousePos(p)
		
		cimgui.Plot_EndPlot()
	}
	cimgui.End()
}`

**Comment by AllenDang** [comment]
Let me take a look.

**Comment by AllenDang** [comment]
Ok, I got it fixed, try newest code.

**Comment by lzytaro** [comment]
> Ok, I got it fixed, try newest code.

Pretty nice， it works！
