### ISSUE TITLE
float32 array arguments

### ISSUE THREAD

**Issue by neclepsio** [AllenDang/cimgui-go#84]
`ColorPicker?V` functions take a `[?]*float32` arguments. I think a `*[?]float32` would be a more practical choice. Compare:

    color := [3]float32{}
    col := [3]*float32{&color[0], &color[1], &color[2]}
    imgui.ColorPicker3V(id, col, cpFlags)

With:

    color := [3]float32{}
    imgui.ColorPicker3V(id, &color, cpFlags)

**Comment by neclepsio** [comment]
Same for `Slider` and `DragFloat`.

**Comment by gucio321** [comment]
Why not.
Need to edit `arguments_wrapper.go`.`simplePtrArrayW(...)

**Comment by gucio321** [comment]
@neclepsio what do you think about doing the same for slices?
currently, it is `[]*type`, can we change it to `*[]type` or even `[]type`? (I mean, if it wouldn't break "pointing ability of pointers", also, iirc slice is pointer itself so we don't need to make it pointer twice)

**Comment by gucio321** [comment]
I think, it is fixed, closing.
