### ISSUE TITLE
Invalid Vec2 wrapper

### ISSUE THREAD

**Issue by ptxmac** [AllenDang/cimgui-go#89]
It seems a lot of top-level functions that return `Vec2` are using invalid wrappers.

As an example lets look at `CursorScreenPos()`:
```go
func CursorScreenPos() Vec2 {
	pOut := &Vec2{}
	pOutArg, pOutFin := wrap[C.ImVec2, *Vec2](pOut)
	defer pOutFin()

	C.igGetCursorScreenPos(pOutArg)
	return *pOut
}

// pOutFin does something like this:

func() {
	*pOut = NewVec2(float32(vec2.x), float32(vec2.y))
}

```

The problem is that `return` is evaluated before defer, which means the value in `*pOut` have already been copied before `pOutFin` is run.

See https://go.dev/play/p/umxyz3I35hT for a minimal demonstration

One solution would be to call the `pOutFin` explicitly after the c call instead of using defer - this ensures the finalizer is completed _before_ the return value is copied

**Comment by WinPooh32** [comment]
Named return value can fix that:
``` go
func CursorScreenPos() (pOut Vec2) {
	pOutArg, pOutFin := wrap[C.ImVec2, *Vec2](&pOut)
	defer pOutFin()

	C.igGetCursorScreenPos(pOutArg)
	return
}
```

**Comment by ptxmac** [comment]
> Named return value can fix that:

Neat! That should be much easier to implement in the generator than my other suggestion

**Comment by gucio321** [comment]
I'm not sure if named return will fix the problem.
I this code the finisher is still called after return statement (so too late) I think, isn't it?
```golang
func CursorScreenPos() (pOut Vec2) {
	pOutArg, pOutFin := wrap[C.ImVec2, *Vec2](&pOut)
	defer pOutFin()

	C.igGetCursorScreenPos(pOutArg)
	return
}
```
IMO _we could_ call finalizer just before return statement, and it _shouldn't_ be much complicated to implement.
Let me take a look

**Comment by ptxmac** [comment]
A quick test shows that @WinPooh32 's suggestion should work: https://go.dev/play/p/tICWuMT4GOz

**Comment by gucio321** [comment]
hehe, your're right.

**Comment by gucio321** [comment]
ok, nuclear solution - I'll get rid of this `defer` call and:
- create wrappers
- call C func
- call finishers

should work and fix this and be less tricky than named-result (i think it may be a kind of bug that GO will fix someday) :smile:

**Comment by WinPooh32** [comment]
``` go
func PlotPixelsToPlotVec2V(pix Vec2, x_axis PlotAxisEnum, y_axis PlotAxisEnum) PlotPoint {
	pOut := &PlotPoint{}
	pOutArg, pOutFin := wrap[C.ImPlotPoint, *PlotPoint](pOut)

	C.ImPlot_PixelsToPlot_Vec2(pOutArg, pix.toC(), C.ImAxis(x_axis), C.ImAxis(y_axis))

	defer func() {
		pOutFin()
	}()

	return *pOut

}
```
https://github.com/AllenDang/cimgui-go/blob/main/cimplot_funcs.go#L949-L951

@gucio321 
Happens again. Empty PlotPoint will be returned.

**Comment by explodingriceballs** [comment]
The issue still persists because defer is being called after the function returns.
```go
func PlotPixelsToPlotVec2V(pix Vec2, x_axis PlotAxisEnum, y_axis PlotAxisEnum) PlotPoint {
	pOut := &PlotPoint{}
	pOutArg, pOutFin := wrap[C.ImPlotPoint, *PlotPoint](pOut)

	C.ImPlot_PixelsToPlot_Vec2(pOutArg, pix.toC(), C.ImAxis(x_axis), C.ImAxis(y_axis))

	//defer func() {
		pOutFin()
	//}()

	return *pOut

}
```

I think the finalizer should be called without the defer block.

**Comment by gucio321** [comment]
I see, let me fix that

**Comment by gucio321** [comment]
https://github.com/gucio321/cimgui-go/tree/hotfix
very strange, it seems that something is going wrong here...
