### ISSUE TITLE
InputText(...) may have wrong arg types

### ISSUE THREAD

**Issue by lzytaro** [AllenDang/cimgui-go#9]
InputText may have wrong arguments with  ```InputText(label string, buf string, buf_size uint64)```.
Should be ```InputText(label string, buf *string)``` ? 

My demo now panic with following code：

```
var inputString string

func showImDemo() {
	cimgui.SetNextWindowPos(cimgui.GetMainViewport().GetPos())
	cimgui.SetNextWindowSize(cimgui.GetMainViewport().GetSize())

	cimgui.Begin("mainwindow")
	cimgui.InputText("input something", inputString, 100)
	cimgui.End()
}
```

**Comment by AllenDang** [comment]
@lzytaro Use `InputTextWithHint` instead, because InputText widgets need manual process, so I exlucde them all, just missed `InputText`. I add it into the exclude list, update to the newest code and this function will be gone.

**Comment by lzytaro** [comment]
> 

Thanks for such a timely reply!
