### ISSUE TITLE
CrossBuild Linux to Windows/Darwin

### ISSUE THREAD

**Issue by GoWeasel** [AllenDang/cimgui-go#95]
![image](https://user-images.githubusercontent.com/61587283/213174726-a542041c-eae5-45e5-89e9-510a6f557a76.png)

**Linux to Linux 64/32 bit:**
GOOS=linux GOARCH=amd64 go build -o bin/example-amd64 .    = work
GOOS=linux GOARCH=386 go build -o bin/example-386 .  = **error**

**Linux to Windows 64/32 bit:**
GOOS=windows GOARCH=amd64 go build -o bin/example-amd64.exe . = **error**
GOOS=windows GOARCH=386 go build -o bin/example-386.exe . = **error**

**Linux to Darwin 64/32 bit:**
GOOS=darwin GOARCH=amd64 go build -o bin/example-amd64-darwin . = **error**
GOOS=darwin GOARCH=386 go build -o bin/example-386-darwin . = **error**

**Allready tested:**
![image](https://user-images.githubusercontent.com/61587283/213181420-55f83810-b999-41a3-a815-fc7012e7f06b.png)

What i am missing?

**Comment by gucio321** [comment]
@GoWeasel you need too handle cgo
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ HOST=x86_64-w64-mingw32 go build -ldflags "-s -w -H=windowsgui -extldflags=-static" -p 4 -v -o YourExeName.exe

**Comment by GoWeasel** [comment]
that works so far  - nice
